---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: tuppr
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.5.6
    digest: sha256:44501f7e65377ab9319884cc7506a0460d45788502c85713e266a4eafcaa3405
  url: oci://ghcr.io/home-operations/charts/tuppr
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tuppr
spec:
  chartRef:
    kind: OCIRepository
    name: tuppr
  interval: 1h
  values:
    replicaCount: 1
    monitoring:
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
    webhook:
      enabled: true
