---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: tuppr
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.3.2
    digest: sha256:181f5e940ef1e3bb155f43ba96e9c4f825da82891ba22cf04fdc29b8ecb82040
  url: oci://ghcr.io/home-operations/charts/tuppr
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tuppr
spec:
  chartRef:
    kind: OCIRepository
    name: tuppr
  interval: 1h
  values:
    replicaCount: 1
    monitoring:
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
    webhook:
      enabled: true
