// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Driscoll.V1
{

    public class ApplicationDefinitionSpecUptimeArgs : global::Pulumi.ResourceArgs
    {
        [Input("http")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Driscoll.V1.ApplicationDefinitionSpecUptimeHttpArgs>? Http { get; set; }

        [Input("ping")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Driscoll.V1.ApplicationDefinitionSpecUptimePingArgs>? Ping { get; set; }

        public ApplicationDefinitionSpecUptimeArgs()
        {
        }
        public static new ApplicationDefinitionSpecUptimeArgs Empty => new ApplicationDefinitionSpecUptimeArgs();
    }
}
