// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.N8n.Outputs
{

    [OutputType]
    public sealed class GetUserSettingsResult
    {
        /// <summary>
        /// Whether to allow SSO manual login for this user
        /// </summary>
        public readonly bool AllowSsoManualLogin;
        /// <summary>
        /// User's preferred theme (e.g., 'light', 'dark')
        /// </summary>
        public readonly string Theme;

        [OutputConstructor]
        private GetUserSettingsResult(
            bool allowSsoManualLogin,

            string theme)
        {
            AllowSsoManualLogin = allowSsoManualLogin;
            Theme = theme;
        }
    }
}
