// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Tailscale.Client.Models
{
    /// <summary>The initiator of the action that generated the event, typically an API or user interface, like the Tailscale admin panel.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ConfigurationAuditLog_origin
    {
        [EnumMember(Value = "ADMIN_CONSOLE")]
        #pragma warning disable CS1591
        ADMIN_CONSOLE,
        #pragma warning restore CS1591
        [EnumMember(Value = "CONFIG_API")]
        #pragma warning disable CS1591
        CONFIG_API,
        #pragma warning restore CS1591
        [EnumMember(Value = "CONTROL")]
        #pragma warning disable CS1591
        CONTROL,
        #pragma warning restore CS1591
        [EnumMember(Value = "IDENTITY_PROVIDER")]
        #pragma warning disable CS1591
        IDENTITY_PROVIDER,
        #pragma warning restore CS1591
        [EnumMember(Value = "NODE")]
        #pragma warning disable CS1591
        NODE,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUPPORT_REQUEST")]
        #pragma warning disable CS1591
        SUPPORT_REQUEST,
        #pragma warning restore CS1591
        [EnumMember(Value = "STRIPE")]
        #pragma warning disable CS1591
        STRIPE,
        #pragma warning restore CS1591
        [EnumMember(Value = "SECURITY_NOTIFICATION")]
        #pragma warning disable CS1591
        SECURITY_NOTIFICATION,
        #pragma warning restore CS1591
        [EnumMember(Value = "LEGAL_NOTIFICATION")]
        #pragma warning disable CS1591
        LEGAL_NOTIFICATION,
        #pragma warning restore CS1591
    }
}
