---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: glance-readonly
rules:
  - apiGroups:
      - ""
      - metrics.k8s.io
    resources:
      - nodes
    verbs:
      - list
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - list
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - list
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - httproutes
    verbs:
      - list
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
      - daemonsets
    verbs:
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: glance-readonly
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: glance-readonly
subjects:
  - kind: Group
    name: glance-readonly
    apiGroup: rbac.authorization.k8s.io
