---
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: outbound
spec:
  type: ingress
  hostnamePrefix: ${CLUSTER_CNAME}-outbound
  replicas: 2
  tags: ["tag:ingress", "tag:apps"]
  proxyClass: default
