---
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: tailnet-outbound
spec:
  type: ingress
  hostnamePrefix: ${CLUSTER_CNAME}-out
  replicas: 2
  tags: ["tag:ingress", "tag:apps"]
  proxyClass: default
