---
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: default
spec:
  statefulSet:
    annotations:
      reloader.stakater.com/auto: "true"
  metrics:
    enable: true
    serviceMonitor:
      enable: true
  # tailscale:
  #   acceptRoutes: true
