// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Proxmox.Inputs
{

    public sealed class VmQemuSerialGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("id", required: true)]
        public Input<double> Id { get; set; } = null!;

        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public VmQemuSerialGetArgs()
        {
        }
        public static new VmQemuSerialGetArgs Empty => new VmQemuSerialGetArgs();
    }
}
