// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Proxmox.Inputs
{

    public sealed class VmQemuVgaArgs : global::Pulumi.ResourceArgs
    {
        [Input("memory")]
        public Input<double>? Memory { get; set; }

        [Input("type")]
        public Input<string>? Type { get; set; }

        public VmQemuVgaArgs()
        {
        }
        public static new VmQemuVgaArgs Empty => new VmQemuVgaArgs();
    }
}
