// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Unifi
{
    [UnifiResourceType("unifi:index/settingMagicSiteToSiteVpn:SettingMagicSiteToSiteVpn")]
    public partial class SettingMagicSiteToSiteVpn : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Whether the Magic Site to Site VPN is enabled.
        /// </summary>
        [Output("enabled")]
        public Output<bool> Enabled { get; private set; } = null!;

        /// <summary>
        /// The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
        /// </summary>
        [Output("site")]
        public Output<string> Site { get; private set; } = null!;


        /// <summary>
        /// Create a SettingMagicSiteToSiteVpn resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public SettingMagicSiteToSiteVpn(string name, SettingMagicSiteToSiteVpnArgs args, CustomResourceOptions? options = null)
            : base("unifi:index/settingMagicSiteToSiteVpn:SettingMagicSiteToSiteVpn", name, args ?? new SettingMagicSiteToSiteVpnArgs(), MakeResourceOptions(options, ""), Utilities.PackageParameterization())
        {
        }

        private SettingMagicSiteToSiteVpn(string name, Input<string> id, SettingMagicSiteToSiteVpnState? state = null, CustomResourceOptions? options = null)
            : base("unifi:index/settingMagicSiteToSiteVpn:SettingMagicSiteToSiteVpn", name, state, MakeResourceOptions(options, id), Utilities.PackageParameterization())
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing SettingMagicSiteToSiteVpn resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static SettingMagicSiteToSiteVpn Get(string name, Input<string> id, SettingMagicSiteToSiteVpnState? state = null, CustomResourceOptions? options = null)
        {
            return new SettingMagicSiteToSiteVpn(name, id, state, options);
        }
    }

    public sealed class SettingMagicSiteToSiteVpnArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether the Magic Site to Site VPN is enabled.
        /// </summary>
        [Input("enabled", required: true)]
        public Input<bool> Enabled { get; set; } = null!;

        /// <summary>
        /// The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
        /// </summary>
        [Input("site")]
        public Input<string>? Site { get; set; }

        public SettingMagicSiteToSiteVpnArgs()
        {
        }
        public static new SettingMagicSiteToSiteVpnArgs Empty => new SettingMagicSiteToSiteVpnArgs();
    }

    public sealed class SettingMagicSiteToSiteVpnState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether the Magic Site to Site VPN is enabled.
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
        /// </summary>
        [Input("site")]
        public Input<string>? Site { get; set; }

        public SettingMagicSiteToSiteVpnState()
        {
        }
        public static new SettingMagicSiteToSiteVpnState Empty => new SettingMagicSiteToSiteVpnState();
    }
}
