// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Authentik.Outputs
{

    [OutputType]
    public sealed class GetGroupsGroupResult
    {
        public readonly string Attributes;
        public readonly bool IsSuperuser;
        public readonly string Name;
        public readonly double NumPk;
        public readonly string Parent;
        public readonly string ParentName;
        public readonly string Pk;
        public readonly ImmutableArray<double> Users;
        public readonly ImmutableArray<Outputs.GetGroupsGroupUsersObjResult> UsersObjs;

        [OutputConstructor]
        private GetGroupsGroupResult(
            string attributes,

            bool isSuperuser,

            string name,

            double numPk,

            string parent,

            string parentName,

            string pk,

            ImmutableArray<double> users,

            ImmutableArray<Outputs.GetGroupsGroupUsersObjResult> usersObjs)
        {
            Attributes = attributes;
            IsSuperuser = isSuperuser;
            Name = name;
            NumPk = numPk;
            Parent = parent;
            ParentName = parentName;
            Pk = pk;
            Users = users;
            UsersObjs = usersObjs;
        }
    }
}
