// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Authentik
{
    [AuthentikResourceType("authentik:index/stageUserWrite:StageUserWrite")]
    public partial class StageUserWrite : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Defaults to `true`.
        /// </summary>
        [Output("createUsersAsInactive")]
        public Output<bool?> CreateUsersAsInactive { get; private set; } = null!;

        [Output("createUsersGroup")]
        public Output<string?> CreateUsersGroup { get; private set; } = null!;

        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("stageUserWriteId")]
        public Output<string> StageUserWriteId { get; private set; } = null!;

        /// <summary>
        /// Allowed values:
        ///   - `never_create`
        ///   - `create_when_required`
        ///   - `always_create`
        ///  Defaults to `create_when_required`.
        /// </summary>
        [Output("userCreationMode")]
        public Output<string?> UserCreationMode { get; private set; } = null!;

        /// <summary>
        /// Defaults to ``.
        /// </summary>
        [Output("userPathTemplate")]
        public Output<string?> UserPathTemplate { get; private set; } = null!;

        /// <summary>
        /// Allowed values:
        ///   - `internal`
        ///   - `external`
        ///   - `service_account`
        ///  Defaults to `external`.
        /// </summary>
        [Output("userType")]
        public Output<string?> UserType { get; private set; } = null!;


        /// <summary>
        /// Create a StageUserWrite resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public StageUserWrite(string name, StageUserWriteArgs? args = null, CustomResourceOptions? options = null)
            : base("authentik:index/stageUserWrite:StageUserWrite", name, args ?? new StageUserWriteArgs(), MakeResourceOptions(options, ""), Utilities.PackageParameterization())
        {
        }

        private StageUserWrite(string name, Input<string> id, StageUserWriteState? state = null, CustomResourceOptions? options = null)
            : base("authentik:index/stageUserWrite:StageUserWrite", name, state, MakeResourceOptions(options, id), Utilities.PackageParameterization())
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing StageUserWrite resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static StageUserWrite Get(string name, Input<string> id, StageUserWriteState? state = null, CustomResourceOptions? options = null)
        {
            return new StageUserWrite(name, id, state, options);
        }
    }

    public sealed class StageUserWriteArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Defaults to `true`.
        /// </summary>
        [Input("createUsersAsInactive")]
        public Input<bool>? CreateUsersAsInactive { get; set; }

        [Input("createUsersGroup")]
        public Input<string>? CreateUsersGroup { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("stageUserWriteId")]
        public Input<string>? StageUserWriteId { get; set; }

        /// <summary>
        /// Allowed values:
        ///   - `never_create`
        ///   - `create_when_required`
        ///   - `always_create`
        ///  Defaults to `create_when_required`.
        /// </summary>
        [Input("userCreationMode")]
        public Input<string>? UserCreationMode { get; set; }

        /// <summary>
        /// Defaults to ``.
        /// </summary>
        [Input("userPathTemplate")]
        public Input<string>? UserPathTemplate { get; set; }

        /// <summary>
        /// Allowed values:
        ///   - `internal`
        ///   - `external`
        ///   - `service_account`
        ///  Defaults to `external`.
        /// </summary>
        [Input("userType")]
        public Input<string>? UserType { get; set; }

        public StageUserWriteArgs()
        {
        }
        public static new StageUserWriteArgs Empty => new StageUserWriteArgs();
    }

    public sealed class StageUserWriteState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Defaults to `true`.
        /// </summary>
        [Input("createUsersAsInactive")]
        public Input<bool>? CreateUsersAsInactive { get; set; }

        [Input("createUsersGroup")]
        public Input<string>? CreateUsersGroup { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("stageUserWriteId")]
        public Input<string>? StageUserWriteId { get; set; }

        /// <summary>
        /// Allowed values:
        ///   - `never_create`
        ///   - `create_when_required`
        ///   - `always_create`
        ///  Defaults to `create_when_required`.
        /// </summary>
        [Input("userCreationMode")]
        public Input<string>? UserCreationMode { get; set; }

        /// <summary>
        /// Defaults to ``.
        /// </summary>
        [Input("userPathTemplate")]
        public Input<string>? UserPathTemplate { get; set; }

        /// <summary>
        /// Allowed values:
        ///   - `internal`
        ///   - `external`
        ///   - `service_account`
        ///  Defaults to `external`.
        /// </summary>
        [Input("userType")]
        public Input<string>? UserType { get; set; }

        public StageUserWriteState()
        {
        }
        public static new StageUserWriteState Empty => new StageUserWriteState();
    }
}
