// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace OnePasswordConnectApi.Client.Models
{
    /// <summary>Some item types, Login and Password, have fields used for autofill. This property indicates that purpose and is required for some item types.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Field_purpose
    {
        [EnumMember(Value = "USERNAME")]
        #pragma warning disable CS1591
        USERNAME,
        #pragma warning restore CS1591
        [EnumMember(Value = "PASSWORD")]
        #pragma warning disable CS1591
        PASSWORD,
        #pragma warning restore CS1591
        [EnumMember(Value = "NOTES")]
        #pragma warning disable CS1591
        NOTES,
        #pragma warning restore CS1591
    }
}
