// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace OnePasswordConnectApi.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Field : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>For fields with a purpose of `PASSWORD` this is the entropy of the value</summary>
        public double? Entropy { get; private set; }
        /// <summary>If value is not present then a new value should be generated for this field</summary>
        public bool? Generate { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The label property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Label { get; set; }
#nullable restore
#else
        public string Label { get; set; }
#endif
        /// <summary>Some item types, Login and Password, have fields used for autofill. This property indicates that purpose and is required for some item types.</summary>
        public global::OnePasswordConnectApi.Client.Models.Field_purpose? Purpose { get; set; }
        /// <summary>The recipe is used in conjunction with the &quot;generate&quot; property to set the character set used to generate a new secure value</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::OnePasswordConnectApi.Client.Models.GeneratorRecipe? Recipe { get; set; }
#nullable restore
#else
        public global::OnePasswordConnectApi.Client.Models.GeneratorRecipe Recipe { get; set; }
#endif
        /// <summary>The section property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::OnePasswordConnectApi.Client.Models.Field_section? Section { get; set; }
#nullable restore
#else
        public global::OnePasswordConnectApi.Client.Models.Field_section Section { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::OnePasswordConnectApi.Client.Models.Field_type? Type { get; set; }
        /// <summary>The value property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Value { get; set; }
#nullable restore
#else
        public string Value { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::OnePasswordConnectApi.Client.Models.Field"/> and sets the default values.
        /// </summary>
        public Field()
        {
            AdditionalData = new Dictionary<string, object>();
            Type = global::OnePasswordConnectApi.Client.Models.Field_type.STRING;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::OnePasswordConnectApi.Client.Models.Field"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::OnePasswordConnectApi.Client.Models.Field CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::OnePasswordConnectApi.Client.Models.Field();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "entropy", n => { Entropy = n.GetDoubleValue(); } },
                { "generate", n => { Generate = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "label", n => { Label = n.GetStringValue(); } },
                { "purpose", n => { Purpose = n.GetEnumValue<global::OnePasswordConnectApi.Client.Models.Field_purpose>(); } },
                { "recipe", n => { Recipe = n.GetObjectValue<global::OnePasswordConnectApi.Client.Models.GeneratorRecipe>(global::OnePasswordConnectApi.Client.Models.GeneratorRecipe.CreateFromDiscriminatorValue); } },
                { "section", n => { Section = n.GetObjectValue<global::OnePasswordConnectApi.Client.Models.Field_section>(global::OnePasswordConnectApi.Client.Models.Field_section.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::OnePasswordConnectApi.Client.Models.Field_type>(); } },
                { "value", n => { Value = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("generate", Generate);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("label", Label);
            writer.WriteEnumValue<global::OnePasswordConnectApi.Client.Models.Field_purpose>("purpose", Purpose);
            writer.WriteObjectValue<global::OnePasswordConnectApi.Client.Models.GeneratorRecipe>("recipe", Recipe);
            writer.WriteObjectValue<global::OnePasswordConnectApi.Client.Models.Field_section>("section", Section);
            writer.WriteEnumValue<global::OnePasswordConnectApi.Client.Models.Field_type>("type", Type);
            writer.WriteStringValue("value", Value);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
