// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace OnePasswordConnectApi.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Field_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "STRING")]
        #pragma warning disable CS1591
        STRING,
        #pragma warning restore CS1591
        [EnumMember(Value = "EMAIL")]
        #pragma warning disable CS1591
        EMAIL,
        #pragma warning restore CS1591
        [EnumMember(Value = "CONCEALED")]
        #pragma warning disable CS1591
        CONCEALED,
        #pragma warning restore CS1591
        [EnumMember(Value = "URL")]
        #pragma warning disable CS1591
        URL,
        #pragma warning restore CS1591
        [EnumMember(Value = "TOTP")]
        #pragma warning disable CS1591
        TOTP,
        #pragma warning restore CS1591
        [EnumMember(Value = "DATE")]
        #pragma warning disable CS1591
        DATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "MONTH_YEAR")]
        #pragma warning disable CS1591
        MONTH_YEAR,
        #pragma warning restore CS1591
        [EnumMember(Value = "MENU")]
        #pragma warning disable CS1591
        MENU,
        #pragma warning restore CS1591
    }
}
