// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace OnePasswordConnectApi.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Vault_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "USER_CREATED")]
        #pragma warning disable CS1591
        USER_CREATED,
        #pragma warning restore CS1591
        [EnumMember(Value = "PERSONAL")]
        #pragma warning disable CS1591
        PERSONAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "EVERYONE")]
        #pragma warning disable CS1591
        EVERYONE,
        #pragma warning restore CS1591
        [EnumMember(Value = "TRANSFER")]
        #pragma warning disable CS1591
        TRANSFER,
        #pragma warning restore CS1591
    }
}
