// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Authentik
{
    [AuthentikResourceType("authentik:index/policyUniquePassword:PolicyUniquePassword")]
    public partial class PolicyUniquePassword : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Defaults to `false`.
        /// </summary>
        [Output("executionLogging")]
        public Output<bool?> ExecutionLogging { get; private set; } = null!;

        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Defaults to `1`.
        /// </summary>
        [Output("numHistoricalPasswords")]
        public Output<double?> NumHistoricalPasswords { get; private set; } = null!;

        /// <summary>
        /// Defaults to `password`.
        /// </summary>
        [Output("passwordField")]
        public Output<string?> PasswordField { get; private set; } = null!;

        [Output("policyUniquePasswordId")]
        public Output<string> PolicyUniquePasswordId { get; private set; } = null!;


        /// <summary>
        /// Create a PolicyUniquePassword resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public PolicyUniquePassword(string name, PolicyUniquePasswordArgs? args = null, CustomResourceOptions? options = null)
            : base("authentik:index/policyUniquePassword:PolicyUniquePassword", name, args ?? new PolicyUniquePasswordArgs(), MakeResourceOptions(options, ""), Utilities.PackageParameterization())
        {
        }

        private PolicyUniquePassword(string name, Input<string> id, PolicyUniquePasswordState? state = null, CustomResourceOptions? options = null)
            : base("authentik:index/policyUniquePassword:PolicyUniquePassword", name, state, MakeResourceOptions(options, id), Utilities.PackageParameterization())
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing PolicyUniquePassword resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static PolicyUniquePassword Get(string name, Input<string> id, PolicyUniquePasswordState? state = null, CustomResourceOptions? options = null)
        {
            return new PolicyUniquePassword(name, id, state, options);
        }
    }

    public sealed class PolicyUniquePasswordArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Defaults to `false`.
        /// </summary>
        [Input("executionLogging")]
        public Input<bool>? ExecutionLogging { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Defaults to `1`.
        /// </summary>
        [Input("numHistoricalPasswords")]
        public Input<double>? NumHistoricalPasswords { get; set; }

        /// <summary>
        /// Defaults to `password`.
        /// </summary>
        [Input("passwordField")]
        public Input<string>? PasswordField { get; set; }

        [Input("policyUniquePasswordId")]
        public Input<string>? PolicyUniquePasswordId { get; set; }

        public PolicyUniquePasswordArgs()
        {
        }
        public static new PolicyUniquePasswordArgs Empty => new PolicyUniquePasswordArgs();
    }

    public sealed class PolicyUniquePasswordState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Defaults to `false`.
        /// </summary>
        [Input("executionLogging")]
        public Input<bool>? ExecutionLogging { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Defaults to `1`.
        /// </summary>
        [Input("numHistoricalPasswords")]
        public Input<double>? NumHistoricalPasswords { get; set; }

        /// <summary>
        /// Defaults to `password`.
        /// </summary>
        [Input("passwordField")]
        public Input<string>? PasswordField { get; set; }

        [Input("policyUniquePasswordId")]
        public Input<string>? PolicyUniquePasswordId { get; set; }

        public PolicyUniquePasswordState()
        {
        }
        public static new PolicyUniquePasswordState Empty => new PolicyUniquePasswordState();
    }
}
