// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Authentik
{
    [AuthentikResourceType("authentik:index/propertyMappingProviderRac:PropertyMappingProviderRac")]
    public partial class PropertyMappingProviderRac : global::Pulumi.CustomResource
    {
        [Output("expression")]
        public Output<string?> Expression { get; private set; } = null!;

        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("propertyMappingProviderRacId")]
        public Output<string> PropertyMappingProviderRacId { get; private set; } = null!;

        /// <summary>
        /// JSON format expected. Use jsonencode() to pass objects. Defaults to `{}`.
        /// </summary>
        [Output("settings")]
        public Output<string?> Settings { get; private set; } = null!;


        /// <summary>
        /// Create a PropertyMappingProviderRac resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public PropertyMappingProviderRac(string name, PropertyMappingProviderRacArgs? args = null, CustomResourceOptions? options = null)
            : base("authentik:index/propertyMappingProviderRac:PropertyMappingProviderRac", name, args ?? new PropertyMappingProviderRacArgs(), MakeResourceOptions(options, ""), Utilities.PackageParameterization())
        {
        }

        private PropertyMappingProviderRac(string name, Input<string> id, PropertyMappingProviderRacState? state = null, CustomResourceOptions? options = null)
            : base("authentik:index/propertyMappingProviderRac:PropertyMappingProviderRac", name, state, MakeResourceOptions(options, id), Utilities.PackageParameterization())
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing PropertyMappingProviderRac resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static PropertyMappingProviderRac Get(string name, Input<string> id, PropertyMappingProviderRacState? state = null, CustomResourceOptions? options = null)
        {
            return new PropertyMappingProviderRac(name, id, state, options);
        }
    }

    public sealed class PropertyMappingProviderRacArgs : global::Pulumi.ResourceArgs
    {
        [Input("expression")]
        public Input<string>? Expression { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("propertyMappingProviderRacId")]
        public Input<string>? PropertyMappingProviderRacId { get; set; }

        /// <summary>
        /// JSON format expected. Use jsonencode() to pass objects. Defaults to `{}`.
        /// </summary>
        [Input("settings")]
        public Input<string>? Settings { get; set; }

        public PropertyMappingProviderRacArgs()
        {
        }
        public static new PropertyMappingProviderRacArgs Empty => new PropertyMappingProviderRacArgs();
    }

    public sealed class PropertyMappingProviderRacState : global::Pulumi.ResourceArgs
    {
        [Input("expression")]
        public Input<string>? Expression { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("propertyMappingProviderRacId")]
        public Input<string>? PropertyMappingProviderRacId { get; set; }

        /// <summary>
        /// JSON format expected. Use jsonencode() to pass objects. Defaults to `{}`.
        /// </summary>
        [Input("settings")]
        public Input<string>? Settings { get; set; }

        public PropertyMappingProviderRacState()
        {
        }
        public static new PropertyMappingProviderRacState Empty => new PropertyMappingProviderRacState();
    }
}
