// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Authentik
{
    [AuthentikResourceType("authentik:index/stageAuthenticatorEndpointGdtc:StageAuthenticatorEndpointGdtc")]
    public partial class StageAuthenticatorEndpointGdtc : global::Pulumi.CustomResource
    {
        [Output("configureFlow")]
        public Output<string?> ConfigureFlow { get; private set; } = null!;

        [Output("credentials")]
        public Output<string> Credentials { get; private set; } = null!;

        [Output("friendlyName")]
        public Output<string?> FriendlyName { get; private set; } = null!;

        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("stageAuthenticatorEndpointGdtcId")]
        public Output<string> StageAuthenticatorEndpointGdtcId { get; private set; } = null!;


        /// <summary>
        /// Create a StageAuthenticatorEndpointGdtc resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public StageAuthenticatorEndpointGdtc(string name, StageAuthenticatorEndpointGdtcArgs args, CustomResourceOptions? options = null)
            : base("authentik:index/stageAuthenticatorEndpointGdtc:StageAuthenticatorEndpointGdtc", name, args ?? new StageAuthenticatorEndpointGdtcArgs(), MakeResourceOptions(options, ""), Utilities.PackageParameterization())
        {
        }

        private StageAuthenticatorEndpointGdtc(string name, Input<string> id, StageAuthenticatorEndpointGdtcState? state = null, CustomResourceOptions? options = null)
            : base("authentik:index/stageAuthenticatorEndpointGdtc:StageAuthenticatorEndpointGdtc", name, state, MakeResourceOptions(options, id), Utilities.PackageParameterization())
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                AdditionalSecretOutputs =
                {
                    "credentials",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing StageAuthenticatorEndpointGdtc resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static StageAuthenticatorEndpointGdtc Get(string name, Input<string> id, StageAuthenticatorEndpointGdtcState? state = null, CustomResourceOptions? options = null)
        {
            return new StageAuthenticatorEndpointGdtc(name, id, state, options);
        }
    }

    public sealed class StageAuthenticatorEndpointGdtcArgs : global::Pulumi.ResourceArgs
    {
        [Input("configureFlow")]
        public Input<string>? ConfigureFlow { get; set; }

        [Input("credentials", required: true)]
        private Input<string>? _credentials;
        public Input<string>? Credentials
        {
            get => _credentials;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _credentials = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("friendlyName")]
        public Input<string>? FriendlyName { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("stageAuthenticatorEndpointGdtcId")]
        public Input<string>? StageAuthenticatorEndpointGdtcId { get; set; }

        public StageAuthenticatorEndpointGdtcArgs()
        {
        }
        public static new StageAuthenticatorEndpointGdtcArgs Empty => new StageAuthenticatorEndpointGdtcArgs();
    }

    public sealed class StageAuthenticatorEndpointGdtcState : global::Pulumi.ResourceArgs
    {
        [Input("configureFlow")]
        public Input<string>? ConfigureFlow { get; set; }

        [Input("credentials")]
        private Input<string>? _credentials;
        public Input<string>? Credentials
        {
            get => _credentials;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _credentials = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("friendlyName")]
        public Input<string>? FriendlyName { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("stageAuthenticatorEndpointGdtcId")]
        public Input<string>? StageAuthenticatorEndpointGdtcId { get; set; }

        public StageAuthenticatorEndpointGdtcState()
        {
        }
        public static new StageAuthenticatorEndpointGdtcState Empty => new StageAuthenticatorEndpointGdtcState();
    }
}
