// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Tailscale.Client.Tailnet.Item.Acl;
using Tailscale.Client.Tailnet.Item.AwsExternalId;
using Tailscale.Client.Tailnet.Item.Contacts;
using Tailscale.Client.Tailnet.Item.Devices;
using Tailscale.Client.Tailnet.Item.Dns;
using Tailscale.Client.Tailnet.Item.Keys;
using Tailscale.Client.Tailnet.Item.Logging;
using Tailscale.Client.Tailnet.Item.Posture;
using Tailscale.Client.Tailnet.Item.Settings;
using Tailscale.Client.Tailnet.Item.UserInvites;
using Tailscale.Client.Tailnet.Item.Users;
using Tailscale.Client.Tailnet.Item.Webhooks;
namespace Tailscale.Client.Tailnet.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \tailnet\{tailnet}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithTailnetItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The acl property</summary>
        public global::Tailscale.Client.Tailnet.Item.Acl.AclRequestBuilder Acl
        {
            get => new global::Tailscale.Client.Tailnet.Item.Acl.AclRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The awsExternalId property</summary>
        public global::Tailscale.Client.Tailnet.Item.AwsExternalId.AwsExternalIdRequestBuilder AwsExternalId
        {
            get => new global::Tailscale.Client.Tailnet.Item.AwsExternalId.AwsExternalIdRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The contacts property</summary>
        public global::Tailscale.Client.Tailnet.Item.Contacts.ContactsRequestBuilder Contacts
        {
            get => new global::Tailscale.Client.Tailnet.Item.Contacts.ContactsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The devices property</summary>
        public global::Tailscale.Client.Tailnet.Item.Devices.DevicesRequestBuilder Devices
        {
            get => new global::Tailscale.Client.Tailnet.Item.Devices.DevicesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The dns property</summary>
        public global::Tailscale.Client.Tailnet.Item.Dns.DnsRequestBuilder Dns
        {
            get => new global::Tailscale.Client.Tailnet.Item.Dns.DnsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The keys property</summary>
        public global::Tailscale.Client.Tailnet.Item.Keys.KeysRequestBuilder Keys
        {
            get => new global::Tailscale.Client.Tailnet.Item.Keys.KeysRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The logging property</summary>
        public global::Tailscale.Client.Tailnet.Item.Logging.LoggingRequestBuilder Logging
        {
            get => new global::Tailscale.Client.Tailnet.Item.Logging.LoggingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The posture property</summary>
        public global::Tailscale.Client.Tailnet.Item.Posture.PostureRequestBuilder Posture
        {
            get => new global::Tailscale.Client.Tailnet.Item.Posture.PostureRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The settings property</summary>
        public global::Tailscale.Client.Tailnet.Item.Settings.SettingsRequestBuilder Settings
        {
            get => new global::Tailscale.Client.Tailnet.Item.Settings.SettingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The userInvites property</summary>
        public global::Tailscale.Client.Tailnet.Item.UserInvites.UserInvitesRequestBuilder UserInvites
        {
            get => new global::Tailscale.Client.Tailnet.Item.UserInvites.UserInvitesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::Tailscale.Client.Tailnet.Item.Users.UsersRequestBuilder Users
        {
            get => new global::Tailscale.Client.Tailnet.Item.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The webhooks property</summary>
        public global::Tailscale.Client.Tailnet.Item.Webhooks.WebhooksRequestBuilder Webhooks
        {
            get => new global::Tailscale.Client.Tailnet.Item.Webhooks.WebhooksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Tailscale.Client.Tailnet.Item.WithTailnetItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTailnetItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tailnet/{tailnet}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Tailscale.Client.Tailnet.Item.WithTailnetItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTailnetItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tailnet/{tailnet}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
