# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: sops-age
  namespace: flux-system
  annotations:
    reloader.stakater.com/auto: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
stringData:
  age.agekey: ENC[AES256_GCM,data:1l9UFFx69GKgG3U7SIXIEu4k1SvbbmG5bShTMo1mO+xVbGdxnAf8eaB5APP5BdYpBUaNdsi1KfvB1JeYViaKYUBxOd2cW4PVzlo=,iv:towMdc1y4hZI/VlPlb75FqrYfEgkhOFi6W1hY/QwovA=,tag:eCQeoSvdu9Tok0axZGMNXg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIZ2ZpWkZpa0U2bERXQkZK
        UU95dEdqR2cyVldpYzJpVW9FMXRwQm9jODAwCjdIbkJQWmo3OEhUTEx4M3pNSWhD
        WGYvU0htNk5ydng0Qkp4MWZiUUNOT2cKLS0tIGQyQS8zdkpMT3BaVDMvbkl3eG10
        WnBmZFFXRmJaRzJabnd4RC9xS3lIb0kKfsS34e5AnSh7T/5FfyVefoEFm9ndb8tN
        1UPvCv7IuoDz1Q94N+Q4DTx35wB7V0z5ohlIZYSrLdra/zH8yFIl8w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eurl2t7pepw66guv8m7lxh5fjhs4t4frsntqjp08lmypwudlsp7qdusgnf
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITUQrdXc2RSt2eno4cTF5
        eTNRUjVhL0tMZXYrbk93U1V5YXh6dDJVcEU4Cmc5WGZKUU5QR1dEZWR5TklCZkVx
        RVYyTFJuQ0FBT2hWWGN0Ty9KbW9EN0kKLS0tICtwU2hMTVcrNWYwTytQaGVNTXUv
        WXpYbkdIZGV0TTZzS3Q4eXo1ZzVWb2MKyoasa6AlgEntbdr+9m0f9BVrdPx6XkTP
        JUE3vDhnS7JQj2xMTHF3RSrbGPJ1VGmiOe3kvRsaoQMsTLUl4LJnFg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age150z0s36kl9vud8728c5e4zqq6nmyywekk76rwvjclcsfc8mrxuuqr0qfg6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-13T03:24:46Z"
  mac: ENC[AES256_GCM,data:zu95GSW/N5pK5ZIX/Zkwt9vkdAsLky8cS3gshs+khVACB8tu9Gt3Q0j5oUCSYbQXr7mbWITNTTAsA2OphyIq3J0ca0/t8/0Ms+WfA0gMf/e3nY+eIHlEHkoJ361O5SBmZrig6SfCGuJlnea34PKjbIVDh2FOt75Cm/+nO23vnPk=,iv:zNB/mA196OkoF1+2xAN3womvARk49UqxGOwr4rYL9O8=,tag:F8Agn2C5OJBnxB95XPOGpQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
