# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: sops-age
  namespace: flux-system
  annotations:
    reloader.stakater.com/auto: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
stringData:
  age.agekey: ENC[AES256_GCM,data:1l9UFFx69GKgG3U7SIXIEu4k1SvbbmG5bShTMo1mO+xVbGdxnAf8eaB5APP5BdYpBUaNdsi1KfvB1JeYViaKYUBxOd2cW4PVzlo=,iv:towMdc1y4hZI/VlPlb75FqrYfEgkhOFi6W1hY/QwovA=,tag:eCQeoSvdu9Tok0axZGMNXg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaR0tnZUIzUzgvMlVZdG9x
        M1RSME9JTEd3M3FENU9wUHFpdHdTUFVkQkZJCnA3dEFzMWN4ZFdNS3phY0RISEVG
        TFQrQ1lSTndsWHpYUEhCdUdyV2tSUjAKLS0tIHF6czdHRlFUUmpCdWlUTmNvKysx
        MmVmYW14enczTmd1b2FPbDBPVmN0Z0EKSPOHPZ1tQ5SD9s7T/6SRRQXYdo4Vii0W
        as7/ueRBEBXau61lFCmzzeMcMy2OvudpkiwBAhnOJ9r7PE17ZAVlkA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eurl2t7pepw66guv8m7lxh5fjhs4t4frsntqjp08lmypwudlsp7qdusgnf
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-13T03:24:46Z"
  mac: ENC[AES256_GCM,data:zu95GSW/N5pK5ZIX/Zkwt9vkdAsLky8cS3gshs+khVACB8tu9Gt3Q0j5oUCSYbQXr7mbWITNTTAsA2OphyIq3J0ca0/t8/0Ms+WfA0gMf/e3nY+eIHlEHkoJ361O5SBmZrig6SfCGuJlnea34PKjbIVDh2FOt75Cm/+nO23vnPk=,iv:zNB/mA196OkoF1+2xAN3womvARk49UqxGOwr4rYL9O8=,tag:F8Agn2C5OJBnxB95XPOGpQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
