// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Proxmox.Outputs
{

    [OutputType]
    public sealed class PoolTimeouts
    {
        public readonly string? Create;
        public readonly string? Default;
        public readonly string? Delete;
        public readonly string? Read;
        public readonly string? Update;

        [OutputConstructor]
        private PoolTimeouts(
            string? create,

            string? @default,

            string? delete,

            string? read,

            string? update)
        {
            Create = create;
            Default = @default;
            Delete = delete;
            Read = read;
            Update = update;
        }
    }
}
