---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app etcd-tasks
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      backup:
        type: cronjob
        cronjob:
          schedule: "12 4 * * *"
          parallelism: 1
          successfulJobsHistory: 1
          failedJobsHistory: 1

        initContainers:
          talosctl:
            image:
              repository: ghcr.io/siderolabs/talosctl
              tag: v1.13.0@sha256:cf5be4c584572787eda0f5818404d2380f041b1022ce85454b25d4e01334fba6
            args:
              - --talosconfig
              - /var/run/secrets/talos.dev/config
              - -n
              - "$(CP_NODE_IP)"
              - -e
              - "$(CP_NODE_IP)"
              - etcd
              - snapshot
              - /data/etcd.snapshot
            env:
              - name: CP_NODE_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP

        containers:
          restic:
            image:
              repository: ghcr.io/ahinko/restic
              tag: 0.18.1@sha256:fa719796676a241c783aa789c0053c92dc92e5d5818722cefb03c5ce163fb904
            workingDir: /data
            args:
              - backup
              - --host
              - kubernetes # set a consistent hostname to avoid restic rescans
              - . # use workingDir to get relative paths in backup
            envFrom:
              - secretRef:
                  name: talos-etcd-restic-keys
            env:
              - name: RESTIC_REPOSITORY
                value: /repository/etcd

        pod:
          hostNetwork: true
          hostPID: true
          nodeSelector:
            node-role.kubernetes.io/control-plane: ""
      defrag:
        type: cronjob
        cronjob:
          schedule: "3 9 * * *" # daily at 09:03
          parallelism: 1
          successfulJobsHistory: 1
          failedJobsHistory: 1

        containers:
          defrag:
            image:
              repository: ghcr.io/siderolabs/talosctl
              tag: v1.13.0@sha256:cf5be4c584572787eda0f5818404d2380f041b1022ce85454b25d4e01334fba6
            args:
              - --talosconfig
              - /var/run/secrets/talos.dev/config
              - -e
              - "$(CP_NODE_IP)"
              - -n
              - "$(CP_NODE_IP)"
              - etcd
              - defrag
            env:
              - name: CP_NODE_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP

        pod:
          hostNetwork: true
          nodeSelector:
            node-role.kubernetes.io/control-plane: ""
      prune:
        type: cronjob
        cronjob:
          schedule: "32 5 1 * *"
          successfulJobsHistory: 1
          failedJobsHistory: 1

        containers:
          restic:
            image:
              repository: ghcr.io/ahinko/restic
              tag: 0.18.1@sha256:fa719796676a241c783aa789c0053c92dc92e5d5818722cefb03c5ce163fb904
            args:
              - forget
              - --keep-last=7 # change me - set retention policy
              - --keep-weekly=4 # see: https://restic.readthedocs.io/en/latest/060_forget.html
              - --prune
            envFrom:
              - secretRef:
                  name: talos-etcd-restic-keys
            env:
              - name: RESTIC_REPOSITORY
                value: /repository/etcd

    persistence:
      serviceaccount:
        type: secret
        name: etcd-talos
        advancedMounts:
          defrag:
            defrag:
              - path: /var/run/secrets/talos.dev
                readOnly: true
          backup:
            talosctl:
              - path: /var/run/secrets/talos.dev
                readOnly: true
      backupdata:
        type: emptyDir
        globalMounts:
          - path: /data
      repository:
        type: nfs
        server: "10.10.10.10"
        path: "/mnt/stash/backup/${CLUSTER_CNAME}/volsync"
