// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Truenas.Outputs
{

    [OutputType]
    public sealed class VmDevice
    {
        /// <summary>
        /// Device attributes specific to device type, check VM resource examples for example device configurations
        /// </summary>
        public readonly ImmutableDictionary<string, string> Attributes;
        /// <summary>
        /// Device ID
        /// </summary>
        public readonly string? Id;
        /// <summary>
        /// Device order
        /// </summary>
        public readonly double? Order;
        /// <summary>
        /// Device type
        /// </summary>
        public readonly string Type;
        /// <summary>
        /// Device VM ID
        /// </summary>
        public readonly double? Vm;

        [OutputConstructor]
        private VmDevice(
            ImmutableDictionary<string, string> attributes,

            string? id,

            double? order,

            string type,

            double? vm)
        {
            Attributes = attributes;
            Id = id;
            Order = order;
            Type = type;
            Vm = vm;
        }
    }
}
