# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reloader.stakater.com/auto: "true"
stringData:
    access-token: ENC[AES256_GCM,data:e7UOrWxz2vaEkkM1guiRjexd7AJE2CUaMiwE/X33xWn+mamEkX5k436VYLlEGOszJbCit2UYAzniSo0zhl5Yj6K/UP91IAo8Qp7yS/TyzRwW7zDTMcSzyfdFuLsSt3S/IQELI2CZtkPykq3H+XvBJQDDjwReGmWnVIScJUzOoUuAoElZkE29Dlv9EAd547XMUWTp3j8/wfRsq8XLYCiCvT25bS4W2noX/o1BpaTnIhsboCrftn/UvRm0bk24W3LmVmreFYU5+2n17iQc1ZEKJnl6tXoyc6MlW13+eac2EzMYez2M78ZH9n2iOZ8kicfDPU6coQGimsoQQqwYcvzFlZfdfLGOA6AKAVyJ3lUfNNaObbqQPe6n/GA7OPLcHMF6Xf677u4IghVXswU7mNDaXDh1E4OPXAcRdKwNORq5QqLUoHDZI358SI8TTkZMXRrIsyOMvtriLEgZuKtcnLOtDcV/54ZbsACJDEAtdTPXsXRQ67Ydp5zv5EXzI1q0VEO3Jj9AQvlu/YlD3XwoY7fztexniqt4l5FizYRkKTYbH4a+5mfN0xOjfGTlMD5KwhlPpZn8mTHQk+RIUWynGQ5e6E26QoIdf7TWi6oGOL2n7myHRBSczFo5eyLDTwUojzyRQ2RaA5Vnpm5SC7/Xoj1RaWtaY/lNTzlT+egMC8sbN1nDGpAv9BGm46h2YnxJRNXbSL762u6coL3dpzNA/Qc3XbhFOzLI3XP2ZDpzKaEsA28/w1JdkWYph1Xw+X+W3aMnZAL7FhdTk4MNVSBvBcg9LKT8n7Ve2PajAZsI/8ATZDj4vn91kJsmFKn8BRYI1qrOZKrgmi3lO9wjX1/Wc4H7U8082w==,iv:fR02X52dVcjbQGvjD7WW4m8HF6T46tsrMFVgSOJg+Xc=,tag:OgjFyOIZe0JlHKPzoOrL1Q==,type:str]
    1password-credentials.json: ENC[AES256_GCM,data:73hMKKcaghbAfkaV50cQhs8k1GhlnlxFUcb+ogSQsVi4/DjHbKDAsh3tyAfl+E6IvhYIy6gC0vfBTr6qSpavpLF2nXSHejTY+kYUh0Tj9khdPdl0xfNd2wWkwe6ZVwkLluU0RCRGjBBQhTPOBgV19PX2goSMPnouFT87PMn5nLEQgShxR762JA1VR4/jvWuX0SJ/diDpJsvisxwWLJCSsMSVh1+pxT4aRa6h6+d0bNhPPUVWa8GskLCG+Jc0LWNM7zTwpl4DAYUt/7BgV9+D2KIv+JEZX5Cv0qPxaA0A3ED3/hNKUaLzDV3hXBMRBeeAawpIrvQOYHu1qAdiLx3fS/U8fTSUDDKVM7SGsu9WGx9nfb3mpraBxraOj1Mwic2GzL21OPVg/wOaWpjxCHy/GQSkWOa1sCNtlMtZkRd5U9WVyKnJgUZN20wggnWSx5GiOVAvxFu51ExFpC8BYVRIts0xpvlLVHbFsZNYpJBPEvW2aYSZKrEV5VRwarTr1o7by8aoEaKrJjZad5tS7i8igbMElhJZ6P14sgaKvJ41RztlZwF/zo+Ts6a5amVXgMV0xwj9vbfFRUUU9i2QBWTak230PfIAWxJUjz3KLg8/27PnhPACOoSJ50Faju6H0vjog3QpCSDrBk5z8gligdm1czexXFCFuROB6aauN7WRvWBUUqXG+eEpoyuSbr/CFTGvrcgxTuq2aW1FFo4k4YkZ2n2WIL0e1A6IyRyLThQOHXrKU0AlbVG5MiXKG0utlUAMbm8qjkCGzKN0PTEcnb7z1WmRbAk/7y9a7WwzHwpSKb14oyrGJPGkmQdZ5/LD+UJIvlJzY6DfMZgZCnVUma4Rl4lVdgABgnELx+BTK5/pVErDZIzBPtMeAzdeB5sdKp+/lZL0y1p5jDoHX3Nk90JeIe/gUsF8qGOFalulw8NyqYgO/nkzMqCp6FB+zPAD5YBwnMlCQLTtCTmh7RM5fpyyECR2NasdlkB8xKdzmVw18F+ZCkyTnJsZkcPCpXQtC9j+PRymhEOJjDI7IF6v1zlggqrKjaiPIh0Cb22LIsPV0ZNqxdzAKuphWGCfiwTBugw+PqQwUbsI0izjrW1shdPhv1u0i8F4WWdqyR7iv6+SzaUhWj+Tjnys5VqDgnqnsFyJaoA0SS7d48tVPxeT27tBNjEtwd+BBJhwffJt6hQ8weuLrpYt01NIYGMxNgUqzLmG45QJWVGJTuAR3EUH5Xr7eTKMiA9zx8gHer9p+/nPhDsLjIz6Y+ogpBsTdAWQtlAGN8sVMFJSOwFgy0xkcuONuv5diAlT1+aWG9HCWgN3ITa8o4n69PEeiKgxtoxdOmicHJYv2AK8Z/xN49XKxsqG78sZSs9Sy58CPOIXCXoNdwF/C83N8+qGV9K7QYXnCPO7QRhBS2BZu/YhwtZAsmv0PJ3eXYhJgRB2kM6H6BbCY/U=,iv:17Q1lFBL+1RfwZhj9BxlfdfeYWn8VRwBeYzfudw8M+A=,tag:L3v0XhI5tsABM1Vw0Cg0cA==,type:str]
sops:
    age:
        - recipient: age1eurl2t7pepw66guv8m7lxh5fjhs4t4frsntqjp08lmypwudlsp7qdusgnf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3R2Z3ZXpVcHB1eHZTQTdJ
            b0k1NExncGQ2cmZxZy9jMVBMeEV3UHJyMTBNCnhQZHlJUktoMS9lQnJYaE1lZTdx
            dWdDcWxmbGVFa0dYamtsU0l1czNyUlUKLS0tIG96bXZMdUpyZU1kbFpSQTZiYzdo
            N3FVUzl4dWFTNnJxNmcwbWJOSkxCUjQKRQXMYviwxSKjyBxDuKxo2AjSF0GppR+5
            XLuZGe3kQck6L7iWZ5Y2GJOGgpcQp8Ja9s7ZGhtKaJA3EnLqV/7vDA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1klzrc4tp666ykn8u4y2nt80n0tcx52lvezrr54zswz55w2pdsgyqhcdfyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUnJMVHVZOHE1eE5GckFs
            SDZQSUhlcVMxSEsxTzJ5N1YvZFZYZHc5WldNCkU4ZDhqaEtWSlhTaWNvc3Z6VjRR
            ZGUyMnZkaTMzV0dZa2VOSE55RVdpclUKLS0tIGpmaHBNR0hZUkQvb1UxL3dlOE9Z
            V0lKc2l0ajUvRFp6ZmJ2WEJxSWZhTVUKeJjg10dtm/Ld2qxaaC1/25j4npVjsgrH
            IWoeOZZg5t0d59i0G8tfTwCO29FietC0Pm6xp2x+A5tT6yFsmgfA6g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age150z0s36kl9vud8728c5e4zqq6nmyywekk76rwvjclcsfc8mrxuuqr0qfg6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuY2d1d2p4SFo4YXNGbHhz
            b0V5N2lWR0dtR0VhNzFPNmxBeHlkUnRTWWdVCjBKMEVnWStQNU9PQ2x6MEkxYVFT
            YVR5QkEzcm8wL2hUazRxWXBPRkdtUEUKLS0tIDR1Z1pNcjVBMmxqeHJtWE03cUM0
            dVlVR21FT3dYZlhYSUpRb3o1dDNWOVEK1AzX8zm2/XJcGkVYeXo5u6crPkfJ0iFn
            4b3R39/hffEgFbuWAMxRgAwRf7SO+6Y7gWvxvk73h5tMgER7Q0yG+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T02:51:04Z"
    mac: ENC[AES256_GCM,data:RVFbv57DhuXRUwo5wG+7rSrScCMPBXcFrnYPpm5ry1JKlDKMSHmad404crNIhJ5RjlyK5OWi4UiobIheGpUuNjqsUB9TYF2zmPakD/lVJZLyxs9vG1NbFPZMLIQuTwxtet/KFzfr2AXrYcrMeIKoXUo5Jb2wtBas/ecLlL2T744=,iv:FRUnawCfoJ+fFDJ4Q1jyOKERjdyDGhQiXaRIxUyUjAk=,tag:Wks0q+tM/BoZsYi5NnXpeQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
