# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reloader.stakater.com/auto: "true"
stringData:
    access-token: ENC[AES256_GCM,data:e7UOrWxz2vaEkkM1guiRjexd7AJE2CUaMiwE/X33xWn+mamEkX5k436VYLlEGOszJbCit2UYAzniSo0zhl5Yj6K/UP91IAo8Qp7yS/TyzRwW7zDTMcSzyfdFuLsSt3S/IQELI2CZtkPykq3H+XvBJQDDjwReGmWnVIScJUzOoUuAoElZkE29Dlv9EAd547XMUWTp3j8/wfRsq8XLYCiCvT25bS4W2noX/o1BpaTnIhsboCrftn/UvRm0bk24W3LmVmreFYU5+2n17iQc1ZEKJnl6tXoyc6MlW13+eac2EzMYez2M78ZH9n2iOZ8kicfDPU6coQGimsoQQqwYcvzFlZfdfLGOA6AKAVyJ3lUfNNaObbqQPe6n/GA7OPLcHMF6Xf677u4IghVXswU7mNDaXDh1E4OPXAcRdKwNORq5QqLUoHDZI358SI8TTkZMXRrIsyOMvtriLEgZuKtcnLOtDcV/54ZbsACJDEAtdTPXsXRQ67Ydp5zv5EXzI1q0VEO3Jj9AQvlu/YlD3XwoY7fztexniqt4l5FizYRkKTYbH4a+5mfN0xOjfGTlMD5KwhlPpZn8mTHQk+RIUWynGQ5e6E26QoIdf7TWi6oGOL2n7myHRBSczFo5eyLDTwUojzyRQ2RaA5Vnpm5SC7/Xoj1RaWtaY/lNTzlT+egMC8sbN1nDGpAv9BGm46h2YnxJRNXbSL762u6coL3dpzNA/Qc3XbhFOzLI3XP2ZDpzKaEsA28/w1JdkWYph1Xw+X+W3aMnZAL7FhdTk4MNVSBvBcg9LKT8n7Ve2PajAZsI/8ATZDj4vn91kJsmFKn8BRYI1qrOZKrgmi3lO9wjX1/Wc4H7U8082w==,iv:fR02X52dVcjbQGvjD7WW4m8HF6T46tsrMFVgSOJg+Xc=,tag:OgjFyOIZe0JlHKPzoOrL1Q==,type:str]
    1password-credentials.json: ENC[AES256_GCM,data:vlmXeomYymLxVoMOxVw62z5g442sWLO4XYYwh8+7115eFzNZiP1XwMHjLa7AtbmvPuNXWwa91JzaztTrUmX9+HDTNN5U3VzUrF9gxQkYP3XqZJXjTV5vtMuQb3W326IiUfQAhsM0I+/I/tl5aMR7O7sWFtWHwftuEriRigoZBbIpEToW1c/DhRwfk4CxrH9pHaogl0XuPY9z3Zu6UUBJJkmEL/QOKWl5tZbhTk97jdcs7ObVtD/p6FSLKAJ/ad6yBWg69Mku3XLwpfy0UtcpldLJIHB9UTTaJ9CJM5lyV86BdF7C2tZz4f6fqI9hDA7MvGeSpEWCyxJ0RgxXoBQazbQp79br/XlfztdJyf6r+X7wx1qbaAq6yfLmugszdcpD7yZQZ7TtlMxTBD45n894DlBbkDcVU97yRf+3KhI3pnXmkSKWeuIHydmPIMMTUgjHu01ReRLHlN6BQWFViWiqZpNTaflvPvHRqk2ZhCTyNsGbmW/wmhijYSSs7FFbWyJY9dFhNdRViRsMcV2yvfpHuZF62Y9rEb6AjsnW6RNSM9E2nkAgo+EQW9wY74vw+C/m2IxmbfRQECcgxk74uhFg4WKZBo5AwwxJwVO1JTmgoadUPV/ZmkvpyINe+uqPKgRMPLR000ZgL58ER+PU3C1l4CMYSBqyunzTsAqXBzvPJ2Qiopn5l2+ErPy5A8PDG4qZcGC6tfayJaSbEHUODH/7INwviyXDy0UalI1fV5YEk9Mnit1fc+duPyUWQ5Q9DbLN60hR0MqbqIJJqejk2b5MaFwBf/LWiMnc3UGEQUNeUpYC3sr9vrJSPRwGlrjQ5TuWloBIQOtcTWVIf487gUImiNOKjW+E0qZAYL89D5TrNoh26/2l4oNm4j5A0A3y1/jJMzvoxhyCkdOyWCEm/Pqih2L/GMzU4adwmM92mbOivYn1hdJ2XOIrEAIpxoaXjeD0uVEubA0lzsZFslchfqw9YAcjhPymVZFviljEAn8gIMssPBNadT+VNb2IpnQY7capVp3XqV12aZYfhiDKpIP9/0Iv6zNRDoNzzaF3gRSEjK2fV8JU7AAvtZUqPHwWmczHZotpvFKqxOvqM/TD6mNCZAO0nFvxEsHlJ+03Tnd7vKjG+wFSvS55CRVTSaOirUkEG+5/PX/0RljvioVxtf/9PNo3jSw5RNrMXu2PsILWgWIQjQv8emUQEW58EwBT+ccL+LSwLYAZ81Uz6VB3NxlzXPGsQmkcUJ9mnctHna0Yyt7q9/IcVAtdM9MH6pN7MRdVrJ0Ey47MuYLZ5fTzn/ImPTTSb2uhxYhzaGySlfo6vZoxOazGEVWhaR8DWPF2wWWsAo/Ct+KK2I3SGJeD/BbnRjK54hZr1E5lQi8StcexJ2BliHLaL8bLWoqjN1oKG8MU7tlBZJi+ZtyjJnVNuVBez2UntQmY34KaeTkM/3w6+BA=,iv:gQwuo3G0ijmJ/Td/0XqTCYcQjG1P7b8Yaag8NVS6wfQ=,tag:2RXxN1AdNpPyChTfOkX3rw==,type:str]
sops:
    age:
        - recipient: age1eurl2t7pepw66guv8m7lxh5fjhs4t4frsntqjp08lmypwudlsp7qdusgnf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3R2Z3ZXpVcHB1eHZTQTdJ
            b0k1NExncGQ2cmZxZy9jMVBMeEV3UHJyMTBNCnhQZHlJUktoMS9lQnJYaE1lZTdx
            dWdDcWxmbGVFa0dYamtsU0l1czNyUlUKLS0tIG96bXZMdUpyZU1kbFpSQTZiYzdo
            N3FVUzl4dWFTNnJxNmcwbWJOSkxCUjQKRQXMYviwxSKjyBxDuKxo2AjSF0GppR+5
            XLuZGe3kQck6L7iWZ5Y2GJOGgpcQp8Ja9s7ZGhtKaJA3EnLqV/7vDA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1klzrc4tp666ykn8u4y2nt80n0tcx52lvezrr54zswz55w2pdsgyqhcdfyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUnJMVHVZOHE1eE5GckFs
            SDZQSUhlcVMxSEsxTzJ5N1YvZFZYZHc5WldNCkU4ZDhqaEtWSlhTaWNvc3Z6VjRR
            ZGUyMnZkaTMzV0dZa2VOSE55RVdpclUKLS0tIGpmaHBNR0hZUkQvb1UxL3dlOE9Z
            V0lKc2l0ajUvRFp6ZmJ2WEJxSWZhTVUKeJjg10dtm/Ld2qxaaC1/25j4npVjsgrH
            IWoeOZZg5t0d59i0G8tfTwCO29FietC0Pm6xp2x+A5tT6yFsmgfA6g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age150z0s36kl9vud8728c5e4zqq6nmyywekk76rwvjclcsfc8mrxuuqr0qfg6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuY2d1d2p4SFo4YXNGbHhz
            b0V5N2lWR0dtR0VhNzFPNmxBeHlkUnRTWWdVCjBKMEVnWStQNU9PQ2x6MEkxYVFT
            YVR5QkEzcm8wL2hUazRxWXBPRkdtUEUKLS0tIDR1Z1pNcjVBMmxqeHJtWE03cUM0
            dVlVR21FT3dYZlhYSUpRb3o1dDNWOVEK1AzX8zm2/XJcGkVYeXo5u6crPkfJ0iFn
            4b3R39/hffEgFbuWAMxRgAwRf7SO+6Y7gWvxvk73h5tMgER7Q0yG+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T02:51:46Z"
    mac: ENC[AES256_GCM,data:twFkmSIA3+ifgbSTMsftLTXAH77pZwisBFZ00MncKiPiyyiYjiXCDaZCTeplsw0D1MeISBX+XRRrHaQ16QxdOzeVLBb4J/jZu4LBwMmKQJGgXyZeJjweSWV/lS/TNSNaYU5Pl4Nl2PXARHyJ+ut1uQJmBoR5c69ZvWfpU8JVCp4=,iv:6Q2zsqz3hsVkUEP4Ko+B6/jlAFPPjw322CddK8rPjHM=,tag:XJDEmV8iGvaTb/G3W967ZQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
