// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Unifi
{
    public static class GetAccount
    {
        public static Task<GetAccountResult> InvokeAsync(GetAccountArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetAccountResult>("unifi:index/getAccount:getAccount", args ?? new GetAccountArgs(), options.WithDefaults(), Utilities.PackageParameterization());

        public static Output<GetAccountResult> Invoke(GetAccountInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetAccountResult>("unifi:index/getAccount:getAccount", args ?? new GetAccountInvokeArgs(), options.WithDefaults());

        public static Output<GetAccountResult> Invoke(GetAccountInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetAccountResult>("unifi:index/getAccount:getAccount", args ?? new GetAccountInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetAccountArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        [Input("site")]
        public string? Site { get; set; }

        public GetAccountArgs()
        {
        }
        public static new GetAccountArgs Empty => new GetAccountArgs();
    }

    public sealed class GetAccountInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("site")]
        public Input<string>? Site { get; set; }

        public GetAccountInvokeArgs()
        {
        }
        public static new GetAccountInvokeArgs Empty => new GetAccountInvokeArgs();
    }


    [OutputType]
    public sealed class GetAccountResult
    {
        public readonly string Id;
        public readonly string Name;
        public readonly string NetworkId;
        public readonly string Password;
        public readonly string Site;
        public readonly double TunnelMediumType;
        public readonly double TunnelType;

        [OutputConstructor]
        private GetAccountResult(
            string id,

            string name,

            string networkId,

            string password,

            string site,

            double tunnelMediumType,

            double tunnelType)
        {
            Id = id;
            Name = name;
            NetworkId = networkId;
            Password = password;
            Site = site;
            TunnelMediumType = tunnelMediumType;
            TunnelType = tunnelType;
        }
    }
}
