// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using OnePasswordConnectApi.Client.Models;
using OnePasswordConnectApi.Client.Vaults.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace OnePasswordConnectApi.Client.Vaults
{
    /// <summary>
    /// Builds and executes requests for operations under \vaults
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class VaultsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the OnePasswordConnectApi.Client.vaults.item collection</summary>
        /// <param name="position">The UUID of the Vault to fetch Items from</param>
        /// <returns>A <see cref="global::OnePasswordConnectApi.Client.Vaults.Item.WithVaultUuItemRequestBuilder"/></returns>
        public global::OnePasswordConnectApi.Client.Vaults.Item.WithVaultUuItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("vaultUuid", position);
                return new global::OnePasswordConnectApi.Client.Vaults.Item.WithVaultUuItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::OnePasswordConnectApi.Client.Vaults.VaultsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public VaultsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/vaults{?filter*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::OnePasswordConnectApi.Client.Vaults.VaultsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public VaultsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/vaults{?filter*}", rawUrl)
        {
        }
        /// <summary>
        /// Get all Vaults
        /// </summary>
        /// <returns>A List&lt;global::OnePasswordConnectApi.Client.Models.Vault&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::OnePasswordConnectApi.Client.Models.ErrorResponse">When receiving a 401 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::OnePasswordConnectApi.Client.Models.Vault>?> GetAsync(Action<RequestConfiguration<global::OnePasswordConnectApi.Client.Vaults.VaultsRequestBuilder.VaultsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::OnePasswordConnectApi.Client.Models.Vault>> GetAsync(Action<RequestConfiguration<global::OnePasswordConnectApi.Client.Vaults.VaultsRequestBuilder.VaultsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::OnePasswordConnectApi.Client.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::OnePasswordConnectApi.Client.Models.Vault>(requestInfo, global::OnePasswordConnectApi.Client.Models.Vault.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Get all Vaults
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::OnePasswordConnectApi.Client.Vaults.VaultsRequestBuilder.VaultsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::OnePasswordConnectApi.Client.Vaults.VaultsRequestBuilder.VaultsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::OnePasswordConnectApi.Client.Vaults.VaultsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::OnePasswordConnectApi.Client.Vaults.VaultsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::OnePasswordConnectApi.Client.Vaults.VaultsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get all Vaults
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class VaultsRequestBuilderGetQueryParameters 
        {
            /// <summary>Filter the Vault collection based on Vault name using SCIM eq filter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter")]
            public string? Filter { get; set; }
#nullable restore
#else
            [QueryParameter("filter")]
            public string Filter { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class VaultsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::OnePasswordConnectApi.Client.Vaults.VaultsRequestBuilder.VaultsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
