#!/bin/sh

set -e
CONFIG_PATH=/app/config/config.json

if [ ! -f "$CONFIG_PATH" ]; then
  echo "{\"repos\": []}" > $CONFIG_PATH
fi
volsync_pgadmin=$(jq -n --arg id "volsync_pgadmin" --arg uri "/shares/volsync/pgadmin" --arg password "RESTIC_PASSWORD" '{id: $id, uri: $uri, password: $password, prunePolicy: { schedule: { disabled: true, clock: "CLOCK_LAST_RUN_TIME" }, maxUnusedPercent: 10 }, checkPolicy: { schedule: {disabled: true, clock: "CLOCK_LAST_RUN_TIME" }, readDataSubsetPercent: 0 }, commandPrefix: {}}');
volsync_uptimeKuma=$(jq -n --arg id "volsync_uptimeKuma" --arg uri "/shares/volsync/uptime-kuma" --arg password "RESTIC_PASSWORD" '{id: $id, uri: $uri, password: $password, prunePolicy: { schedule: { disabled: true, clock: "CLOCK_LAST_RUN_TIME" }, maxUnusedPercent: 10 }, checkPolicy: { schedule: {disabled: true, clock: "CLOCK_LAST_RUN_TIME" }, readDataSubsetPercent: 0 }, commandPrefix: {}}');
volsync_autokuma=$(jq -n --arg id "volsync_autokuma" --arg uri "/shares/volsync/autokuma" --arg password "RESTIC_PASSWORD" '{id: $id, uri: $uri, password: $password, prunePolicy: { schedule: { disabled: true, clock: "CLOCK_LAST_RUN_TIME" }, maxUnusedPercent: 10 }, checkPolicy: { schedule: {disabled: true, clock: "CLOCK_LAST_RUN_TIME" }, readDataSubsetPercent: 0 }, commandPrefix: {}}');
volsync_authentik=$(jq -n --arg id "volsync_authentik" --arg uri "/shares/volsync/authentik" --arg password "RESTIC_PASSWORD" '{id: $id, uri: $uri, password: $password, prunePolicy: { schedule: { disabled: true, clock: "CLOCK_LAST_RUN_TIME" }, maxUnusedPercent: 10 }, checkPolicy: { schedule: {disabled: true, clock: "CLOCK_LAST_RUN_TIME" }, readDataSubsetPercent: 0 }, commandPrefix: {}}');
volsync_matter=$(jq -n --arg id "volsync_matter" --arg uri "/shares/volsync/matter" --arg password "RESTIC_PASSWORD" '{id: $id, uri: $uri, password: $password, prunePolicy: { schedule: { disabled: true, clock: "CLOCK_LAST_RUN_TIME" }, maxUnusedPercent: 10 }, checkPolicy: { schedule: {disabled: true, clock: "CLOCK_LAST_RUN_TIME" }, readDataSubsetPercent: 0 }, commandPrefix: {}}');
volsync_homeAssistant=$(jq -n --arg id "volsync_homeAssistant" --arg uri "/shares/volsync/home-assistant" --arg password "RESTIC_PASSWORD" '{id: $id, uri: $uri, password: $password, prunePolicy: { schedule: { disabled: true, clock: "CLOCK_LAST_RUN_TIME" }, maxUnusedPercent: 10 }, checkPolicy: { schedule: {disabled: true, clock: "CLOCK_LAST_RUN_TIME" }, readDataSubsetPercent: 0 }, commandPrefix: {}}');
volsync_networkUpsTools=$(jq -n --arg id "volsync_networkUpsTools" --arg uri "/shares/volsync/network-ups-tools" --arg password "RESTIC_PASSWORD" '{id: $id, uri: $uri, password: $password, prunePolicy: { schedule: { disabled: true, clock: "CLOCK_LAST_RUN_TIME" }, maxUnusedPercent: 10 }, checkPolicy: { schedule: {disabled: true, clock: "CLOCK_LAST_RUN_TIME" }, readDataSubsetPercent: 0 }, commandPrefix: {}}');
volsync_scrypted=$(jq -n --arg id "volsync_scrypted" --arg uri "/shares/volsync/scrypted" --arg password "RESTIC_PASSWORD" '{id: $id, uri: $uri, password: $password, prunePolicy: { schedule: { disabled: true, clock: "CLOCK_LAST_RUN_TIME" }, maxUnusedPercent: 10 }, checkPolicy: { schedule: {disabled: true, clock: "CLOCK_LAST_RUN_TIME" }, readDataSubsetPercent: 0 }, commandPrefix: {}}');
volsync_plex=$(jq -n --arg id "volsync_plex" --arg uri "/shares/volsync/plex" --arg password "RESTIC_PASSWORD" '{id: $id, uri: $uri, password: $password, prunePolicy: { schedule: { disabled: true, clock: "CLOCK_LAST_RUN_TIME" }, maxUnusedPercent: 10 }, checkPolicy: { schedule: {disabled: true, clock: "CLOCK_LAST_RUN_TIME" }, readDataSubsetPercent: 0 }, commandPrefix: {}}');
volsync_tautulli=$(jq -n --arg id "volsync_tautulli" --arg uri "/shares/volsync/tautulli" --arg password "RESTIC_PASSWORD" '{id: $id, uri: $uri, password: $password, prunePolicy: { schedule: { disabled: true, clock: "CLOCK_LAST_RUN_TIME" }, maxUnusedPercent: 10 }, checkPolicy: { schedule: {disabled: true, clock: "CLOCK_LAST_RUN_TIME" }, readDataSubsetPercent: 0 }, commandPrefix: {}}');
volsync_backrest=$(jq -n --arg id "volsync_backrest" --arg uri "/shares/volsync/backrest" --arg password "RESTIC_PASSWORD" '{id: $id, uri: $uri, password: $password, prunePolicy: { schedule: { disabled: true, clock: "CLOCK_LAST_RUN_TIME" }, maxUnusedPercent: 10 }, checkPolicy: { schedule: {disabled: true, clock: "CLOCK_LAST_RUN_TIME" }, readDataSubsetPercent: 0 }, commandPrefix: {}}');
volsync_resticServer=$(jq -n --arg id "volsync_resticServer" --arg uri "/shares/volsync/restic-server" --arg password "RESTIC_PASSWORD" '{id: $id, uri: $uri, password: $password, prunePolicy: { schedule: { disabled: true, clock: "CLOCK_LAST_RUN_TIME" }, maxUnusedPercent: 10 }, checkPolicy: { schedule: {disabled: true, clock: "CLOCK_LAST_RUN_TIME" }, readDataSubsetPercent: 0 }, commandPrefix: {}}');
cat $CONFIG_PATH | jq '.instance = "${CLUSTER_CNAME}"' | jq '.version = 4' | jq '.auth.disabled = true' | jq '.plans = []' | jq '.repos = []' | jq --argjson repo "$volsync_pgadmin" '.repos += [$repo]' | jq --argjson repo "$volsync_uptimeKuma" '.repos += [$repo]' | jq --argjson repo "$volsync_autokuma" '.repos += [$repo]' | jq --argjson repo "$volsync_authentik" '.repos += [$repo]' | jq --argjson repo "$volsync_matter" '.repos += [$repo]' | jq --argjson repo "$volsync_homeAssistant" '.repos += [$repo]' | jq --argjson repo "$volsync_networkUpsTools" '.repos += [$repo]' | jq --argjson repo "$volsync_scrypted" '.repos += [$repo]' | jq --argjson repo "$volsync_plex" '.repos += [$repo]' | jq --argjson repo "$volsync_tautulli" '.repos += [$repo]' | jq --argjson repo "$volsync_backrest" '.repos += [$repo]' | jq --argjson repo "$volsync_resticServer" '.repos += [$repo]' | jq '.repos |= (group_by(.id) | map(.[0]))' | tee $CONFIG_PATH
cat $CONFIG_PATH | jq
