// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Tailscale.Client.Tailnet.Item.Logging.Configuration
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetEventQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ADMIN_CONSOLE.LOGIN")]
        #pragma warning disable CS1591
        ADMIN_CONSOLELOGIN,
        #pragma warning restore CS1591
        [EnumMember(Value = "ADMIN_CONSOLE.LOGOUT")]
        #pragma warning disable CS1591
        ADMIN_CONSOLELOGOUT,
        #pragma warning restore CS1591
        [EnumMember(Value = "API_KEY.CREATE")]
        #pragma warning disable CS1591
        API_KEYCREATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "API_KEY.EXPIRED")]
        #pragma warning disable CS1591
        API_KEYEXPIRED,
        #pragma warning restore CS1591
        [EnumMember(Value = "API_KEY.REVOKE")]
        #pragma warning disable CS1591
        API_KEYREVOKE,
        #pragma warning restore CS1591
        [EnumMember(Value = "BILLING.CANCEL.SUBSCRIPTION")]
        #pragma warning disable CS1591
        BILLINGCANCELSUBSCRIPTION,
        #pragma warning restore CS1591
        [EnumMember(Value = "BILLING.CREATE.SUBSCRIPTION")]
        #pragma warning disable CS1591
        BILLINGCREATESUBSCRIPTION,
        #pragma warning restore CS1591
        [EnumMember(Value = "BILLING.UPDATE.ADDRESS")]
        #pragma warning disable CS1591
        BILLINGUPDATEADDRESS,
        #pragma warning restore CS1591
        [EnumMember(Value = "BILLING.UPDATE.BILLING_OWNER")]
        #pragma warning disable CS1591
        BILLINGUPDATEBILLING_OWNER,
        #pragma warning restore CS1591
        [EnumMember(Value = "BILLING.UPDATE.EMAIL")]
        #pragma warning disable CS1591
        BILLINGUPDATEEMAIL,
        #pragma warning restore CS1591
        [EnumMember(Value = "BILLING.UPDATE.PAYMENT_INFO")]
        #pragma warning disable CS1591
        BILLINGUPDATEPAYMENT_INFO,
        #pragma warning restore CS1591
        [EnumMember(Value = "BILLING.UPDATE.STRIPE_CUSTOMER_ID")]
        #pragma warning disable CS1591
        BILLINGUPDATESTRIPE_CUSTOMER_ID,
        #pragma warning restore CS1591
        [EnumMember(Value = "BILLING.UPDATE.SUBSCRIPTION")]
        #pragma warning disable CS1591
        BILLINGUPDATESUBSCRIPTION,
        #pragma warning restore CS1591
        [EnumMember(Value = "FAILED_REQUEST.UPDATE")]
        #pragma warning disable CS1591
        FAILED_REQUESTUPDATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "GROUP.PUSH_GROUP.ATTRIBUTES")]
        #pragma warning disable CS1591
        GROUPPUSH_GROUPATTRIBUTES,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVITE.ACCEPT.FEATURE")]
        #pragma warning disable CS1591
        INVITEACCEPTFEATURE,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVITE.ACCEPT.NODE_SHARE")]
        #pragma warning disable CS1591
        INVITEACCEPTNODE_SHARE,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVITE.ACCEPT.TAILNET_INVITE")]
        #pragma warning disable CS1591
        INVITEACCEPTTAILNET_INVITE,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVITE.CREATE.FEATURE")]
        #pragma warning disable CS1591
        INVITECREATEFEATURE,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVITE.CREATE.NODE_SHARE")]
        #pragma warning disable CS1591
        INVITECREATENODE_SHARE,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVITE.CREATE.TAILNET_INVITE")]
        #pragma warning disable CS1591
        INVITECREATETAILNET_INVITE,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVITE.DELETE.NODE_SHARE")]
        #pragma warning disable CS1591
        INVITEDELETENODE_SHARE,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVITE.DELETE.TAILNET_INVITE")]
        #pragma warning disable CS1591
        INVITEDELETETAILNET_INVITE,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVITE.RESEND.NODE_SHARE")]
        #pragma warning disable CS1591
        INVITERESENDNODE_SHARE,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVITE.RESEND.TAILNET_INVITE")]
        #pragma warning disable CS1591
        INVITERESENDTAILNET_INVITE,
        #pragma warning restore CS1591
        [EnumMember(Value = "NODE.APPROVE")]
        #pragma warning disable CS1591
        NODEAPPROVE,
        #pragma warning restore CS1591
        [EnumMember(Value = "NODE.CREATE")]
        #pragma warning disable CS1591
        NODECREATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "NODE.CREATE.ATTRIBUTES")]
        #pragma warning disable CS1591
        NODECREATEATTRIBUTES,
        #pragma warning restore CS1591
        [EnumMember(Value = "NODE.DELETE")]
        #pragma warning disable CS1591
        NODEDELETE,
        #pragma warning restore CS1591
        [EnumMember(Value = "NODE.DELETE.ATTRIBUTES")]
        #pragma warning disable CS1591
        NODEDELETEATTRIBUTES,
        #pragma warning restore CS1591
        [EnumMember(Value = "NODE.DISABLE.KEY_EXPIRY")]
        #pragma warning disable CS1591
        NODEDISABLEKEY_EXPIRY,
        #pragma warning restore CS1591
        [EnumMember(Value = "NODE.DISCONNECT_NODE.CLIENT_LOG")]
        #pragma warning disable CS1591
        NODEDISCONNECT_NODECLIENT_LOG,
        #pragma warning restore CS1591
        [EnumMember(Value = "NODE.ENABLE.KEY_EXPIRY")]
        #pragma warning disable CS1591
        NODEENABLEKEY_EXPIRY,
        #pragma warning restore CS1591
        [EnumMember(Value = "NODE.EXPIRED.KEY_EXPIRY_TIME")]
        #pragma warning disable CS1591
        NODEEXPIREDKEY_EXPIRY_TIME,
        #pragma warning restore CS1591
        [EnumMember(Value = "NODE.LOGIN")]
        #pragma warning disable CS1591
        NODELOGIN,
        #pragma warning restore CS1591
        [EnumMember(Value = "NODE.LOGOUT")]
        #pragma warning disable CS1591
        NODELOGOUT,
        #pragma warning restore CS1591
        [EnumMember(Value = "NODE.REVOKE")]
        #pragma warning disable CS1591
        NODEREVOKE,
        #pragma warning restore CS1591
        [EnumMember(Value = "NODE.UPDATE.ACL_TAGS")]
        #pragma warning disable CS1591
        NODEUPDATEACL_TAGS,
        #pragma warning restore CS1591
        [EnumMember(Value = "NODE.UPDATE.ALLOWED_IPS")]
        #pragma warning disable CS1591
        NODEUPDATEALLOWED_IPS,
        #pragma warning restore CS1591
        [EnumMember(Value = "NODE.UPDATE.ATTRIBUTES")]
        #pragma warning disable CS1591
        NODEUPDATEATTRIBUTES,
        #pragma warning restore CS1591
        [EnumMember(Value = "NODE.UPDATE.AUTO_APPROVED_ROUTES")]
        #pragma warning disable CS1591
        NODEUPDATEAUTO_APPROVED_ROUTES,
        #pragma warning restore CS1591
        [EnumMember(Value = "NODE.UPDATE.EXIT_NODE")]
        #pragma warning disable CS1591
        NODEUPDATEEXIT_NODE,
        #pragma warning restore CS1591
        [EnumMember(Value = "NODE.UPDATE.KEY_EXPIRY_TIME")]
        #pragma warning disable CS1591
        NODEUPDATEKEY_EXPIRY_TIME,
        #pragma warning restore CS1591
        [EnumMember(Value = "NODE.UPDATE.MACHINE_NAME")]
        #pragma warning disable CS1591
        NODEUPDATEMACHINE_NAME,
        #pragma warning restore CS1591
        [EnumMember(Value = "NODE.UPDATE.POSTURE_IDENTITY")]
        #pragma warning disable CS1591
        NODEUPDATEPOSTURE_IDENTITY,
        #pragma warning restore CS1591
        [EnumMember(Value = "NODE.UPDATE.TKA")]
        #pragma warning disable CS1591
        NODEUPDATETKA,
        #pragma warning restore CS1591
        [EnumMember(Value = "SHARE.CREATE")]
        #pragma warning disable CS1591
        SHARECREATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "SHARE.DELETE")]
        #pragma warning disable CS1591
        SHAREDELETE,
        #pragma warning restore CS1591
        [EnumMember(Value = "SHARE.UPDATE")]
        #pragma warning disable CS1591
        SHAREUPDATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.ACCEPT.FEATURE")]
        #pragma warning disable CS1591
        TAILNETACCEPTFEATURE,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.CREATE")]
        #pragma warning disable CS1591
        TAILNETCREATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.CREATE.LOGSTREAM_ENDPOINT")]
        #pragma warning disable CS1591
        TAILNETCREATELOGSTREAM_ENDPOINT,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.CREATE.POSTURE_INTEGRATION")]
        #pragma warning disable CS1591
        TAILNETCREATEPOSTURE_INTEGRATION,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.CREATE.TKA")]
        #pragma warning disable CS1591
        TAILNETCREATETKA,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.DELETE.LOGSTREAM_ENDPOINT")]
        #pragma warning disable CS1591
        TAILNETDELETELOGSTREAM_ENDPOINT,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.DELETE.POSTURE_INTEGRATION")]
        #pragma warning disable CS1591
        TAILNETDELETEPOSTURE_INTEGRATION,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.DELETE.TKA")]
        #pragma warning disable CS1591
        TAILNETDELETETKA,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.DISABLE.COLLECT_POSTURE_IDENTITY")]
        #pragma warning disable CS1591
        TAILNETDISABLECOLLECT_POSTURE_IDENTITY,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.DISABLE.COLLECT_SERVICES")]
        #pragma warning disable CS1591
        TAILNETDISABLECOLLECT_SERVICES,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.DISABLE.FILE_SHARING")]
        #pragma warning disable CS1591
        TAILNETDISABLEFILE_SHARING,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.DISABLE.GEOSTEERING")]
        #pragma warning disable CS1591
        TAILNETDISABLEGEOSTEERING,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.DISABLE.HTTPS")]
        #pragma warning disable CS1591
        TAILNETDISABLEHTTPS,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.DISABLE.LOG_EXIT_FLOWS")]
        #pragma warning disable CS1591
        TAILNETDISABLELOG_EXIT_FLOWS,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.DISABLE.MACHINE_APPROVAL_NEEDED")]
        #pragma warning disable CS1591
        TAILNETDISABLEMACHINE_APPROVAL_NEEDED,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.DISABLE.MAGIC_DNS")]
        #pragma warning disable CS1591
        TAILNETDISABLEMAGIC_DNS,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.DISABLE.MULLVAD_VPN")]
        #pragma warning disable CS1591
        TAILNETDISABLEMULLVAD_VPN,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.DISABLE.NETWORK_FLOW_LOGGING")]
        #pragma warning disable CS1591
        TAILNETDISABLENETWORK_FLOW_LOGGING,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.DISABLE.SCIM")]
        #pragma warning disable CS1591
        TAILNETDISABLESCIM,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.DISABLE.TKA")]
        #pragma warning disable CS1591
        TAILNETDISABLETKA,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.DISABLE.USER_APPROVAL_REQUIRED")]
        #pragma warning disable CS1591
        TAILNETDISABLEUSER_APPROVAL_REQUIRED,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.ENABLE.COLLECT_POSTURE_IDENTITY")]
        #pragma warning disable CS1591
        TAILNETENABLECOLLECT_POSTURE_IDENTITY,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.ENABLE.COLLECT_SERVICES")]
        #pragma warning disable CS1591
        TAILNETENABLECOLLECT_SERVICES,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.ENABLE.FILE_SHARING")]
        #pragma warning disable CS1591
        TAILNETENABLEFILE_SHARING,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.ENABLE.GEOSTEERING")]
        #pragma warning disable CS1591
        TAILNETENABLEGEOSTEERING,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.ENABLE.HTTPS")]
        #pragma warning disable CS1591
        TAILNETENABLEHTTPS,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.ENABLE.LOG_EXIT_FLOWS")]
        #pragma warning disable CS1591
        TAILNETENABLELOG_EXIT_FLOWS,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.ENABLE.MACHINE_APPROVAL_NEEDED")]
        #pragma warning disable CS1591
        TAILNETENABLEMACHINE_APPROVAL_NEEDED,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.ENABLE.MAGIC_DNS")]
        #pragma warning disable CS1591
        TAILNETENABLEMAGIC_DNS,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.ENABLE.MULLVAD_VPN")]
        #pragma warning disable CS1591
        TAILNETENABLEMULLVAD_VPN,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.ENABLE.NETWORK_FLOW_LOGGING")]
        #pragma warning disable CS1591
        TAILNETENABLENETWORK_FLOW_LOGGING,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.ENABLE.SCIM")]
        #pragma warning disable CS1591
        TAILNETENABLESCIM,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.ENABLE.TKA")]
        #pragma warning disable CS1591
        TAILNETENABLETKA,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.ENABLE.USER_APPROVAL_REQUIRED")]
        #pragma warning disable CS1591
        TAILNETENABLEUSER_APPROVAL_REQUIRED,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.JOIN")]
        #pragma warning disable CS1591
        TAILNETJOIN,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.JOIN_WAITLIST.FEATURE")]
        #pragma warning disable CS1591
        TAILNETJOIN_WAITLISTFEATURE,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.LEAVE")]
        #pragma warning disable CS1591
        TAILNETLEAVE,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.UPDATE.ACCOUNT_EMAIL")]
        #pragma warning disable CS1591
        TAILNETUPDATEACCOUNT_EMAIL,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.UPDATE.ACL")]
        #pragma warning disable CS1591
        TAILNETUPDATEACL,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.UPDATE.DNS_CONFIG")]
        #pragma warning disable CS1591
        TAILNETUPDATEDNS_CONFIG,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.UPDATE.LOGSTREAM_ENDPOINT")]
        #pragma warning disable CS1591
        TAILNETUPDATELOGSTREAM_ENDPOINT,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.UPDATE.MAX_KEY_DURATION")]
        #pragma warning disable CS1591
        TAILNETUPDATEMAX_KEY_DURATION,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.UPDATE.POSTURE_INTEGRATION")]
        #pragma warning disable CS1591
        TAILNETUPDATEPOSTURE_INTEGRATION,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.UPDATE.SECURITY_EMAIL")]
        #pragma warning disable CS1591
        TAILNETUPDATESECURITY_EMAIL,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.UPDATE.SUPPORT_EMAIL")]
        #pragma warning disable CS1591
        TAILNETUPDATESUPPORT_EMAIL,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.UPDATE.TCD")]
        #pragma warning disable CS1591
        TAILNETUPDATETCD,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.UPDATE.TKA")]
        #pragma warning disable CS1591
        TAILNETUPDATETKA,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.VERIFY.ACCOUNT_EMAIL")]
        #pragma warning disable CS1591
        TAILNETVERIFYACCOUNT_EMAIL,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.VERIFY.SECURITY_EMAIL")]
        #pragma warning disable CS1591
        TAILNETVERIFYSECURITY_EMAIL,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET.VERIFY.SUPPORT_EMAIL")]
        #pragma warning disable CS1591
        TAILNETVERIFYSUPPORT_EMAIL,
        #pragma warning restore CS1591
        [EnumMember(Value = "USER.APPROVE")]
        #pragma warning disable CS1591
        USERAPPROVE,
        #pragma warning restore CS1591
        [EnumMember(Value = "USER.CREATE")]
        #pragma warning disable CS1591
        USERCREATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "USER.DELETE")]
        #pragma warning disable CS1591
        USERDELETE,
        #pragma warning restore CS1591
        [EnumMember(Value = "USER.INVITE")]
        #pragma warning disable CS1591
        USERINVITE,
        #pragma warning restore CS1591
        [EnumMember(Value = "USER.PUSH_USER.ATTRIBUTES")]
        #pragma warning disable CS1591
        USERPUSH_USERATTRIBUTES,
        #pragma warning restore CS1591
        [EnumMember(Value = "USER.RESEND.TAILNET_INVITE")]
        #pragma warning disable CS1591
        USERRESENDTAILNET_INVITE,
        #pragma warning restore CS1591
        [EnumMember(Value = "USER.RESTORE")]
        #pragma warning disable CS1591
        USERRESTORE,
        #pragma warning restore CS1591
        [EnumMember(Value = "USER.SUSPEND")]
        #pragma warning disable CS1591
        USERSUSPEND,
        #pragma warning restore CS1591
        [EnumMember(Value = "USER.UPDATE.USER_ROLE")]
        #pragma warning disable CS1591
        USERUPDATEUSER_ROLE,
        #pragma warning restore CS1591
        [EnumMember(Value = "WEBHOOK_ENDPOINT.CREATE")]
        #pragma warning disable CS1591
        WEBHOOK_ENDPOINTCREATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "WEBHOOK_ENDPOINT.DELETE")]
        #pragma warning disable CS1591
        WEBHOOK_ENDPOINTDELETE,
        #pragma warning restore CS1591
        [EnumMember(Value = "WEBHOOK_ENDPOINT.UPDATE.SECRET")]
        #pragma warning disable CS1591
        WEBHOOK_ENDPOINTUPDATESECRET,
        #pragma warning restore CS1591
        [EnumMember(Value = "WEBHOOK_ENDPOINT.UPDATE.SUBSCRIBED_EVENTS")]
        #pragma warning disable CS1591
        WEBHOOK_ENDPOINTUPDATESUBSCRIBED_EVENTS,
        #pragma warning restore CS1591
        [EnumMember(Value = "WEB_INTERFACE.LOGIN")]
        #pragma warning disable CS1591
        WEB_INTERFACELOGIN,
        #pragma warning restore CS1591
        [EnumMember(Value = "WEB_INTERFACE.LOGOUT")]
        #pragma warning disable CS1591
        WEB_INTERFACELOGOUT,
        #pragma warning restore CS1591
    }
}
