// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Authentik
{
    [AuthentikResourceType("authentik:index/enterpriseLicense:EnterpriseLicense")]
    public partial class EnterpriseLicense : global::Pulumi.CustomResource
    {
        [Output("enterpriseLicenseId")]
        public Output<string> EnterpriseLicenseId { get; private set; } = null!;

        /// <summary>
        /// Generated.
        /// </summary>
        [Output("expiry")]
        public Output<double> Expiry { get; private set; } = null!;

        /// <summary>
        /// Generated.
        /// </summary>
        [Output("externalUsers")]
        public Output<double> ExternalUsers { get; private set; } = null!;

        /// <summary>
        /// Generated.
        /// </summary>
        [Output("internalUsers")]
        public Output<double> InternalUsers { get; private set; } = null!;

        [Output("key")]
        public Output<string> Key { get; private set; } = null!;

        /// <summary>
        /// Generated.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;


        /// <summary>
        /// Create a EnterpriseLicense resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public EnterpriseLicense(string name, EnterpriseLicenseArgs args, CustomResourceOptions? options = null)
            : base("authentik:index/enterpriseLicense:EnterpriseLicense", name, args ?? new EnterpriseLicenseArgs(), MakeResourceOptions(options, ""), Utilities.PackageParameterization())
        {
        }

        private EnterpriseLicense(string name, Input<string> id, EnterpriseLicenseState? state = null, CustomResourceOptions? options = null)
            : base("authentik:index/enterpriseLicense:EnterpriseLicense", name, state, MakeResourceOptions(options, id), Utilities.PackageParameterization())
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                AdditionalSecretOutputs =
                {
                    "key",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing EnterpriseLicense resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static EnterpriseLicense Get(string name, Input<string> id, EnterpriseLicenseState? state = null, CustomResourceOptions? options = null)
        {
            return new EnterpriseLicense(name, id, state, options);
        }
    }

    public sealed class EnterpriseLicenseArgs : global::Pulumi.ResourceArgs
    {
        [Input("enterpriseLicenseId")]
        public Input<string>? EnterpriseLicenseId { get; set; }

        [Input("key", required: true)]
        private Input<string>? _key;
        public Input<string>? Key
        {
            get => _key;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _key = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public EnterpriseLicenseArgs()
        {
        }
        public static new EnterpriseLicenseArgs Empty => new EnterpriseLicenseArgs();
    }

    public sealed class EnterpriseLicenseState : global::Pulumi.ResourceArgs
    {
        [Input("enterpriseLicenseId")]
        public Input<string>? EnterpriseLicenseId { get; set; }

        /// <summary>
        /// Generated.
        /// </summary>
        [Input("expiry")]
        public Input<double>? Expiry { get; set; }

        /// <summary>
        /// Generated.
        /// </summary>
        [Input("externalUsers")]
        public Input<double>? ExternalUsers { get; set; }

        /// <summary>
        /// Generated.
        /// </summary>
        [Input("internalUsers")]
        public Input<double>? InternalUsers { get; set; }

        [Input("key")]
        private Input<string>? _key;
        public Input<string>? Key
        {
            get => _key;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _key = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Generated.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public EnterpriseLicenseState()
        {
        }
        public static new EnterpriseLicenseState Empty => new EnterpriseLicenseState();
    }
}
