// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Authentik
{
    public static class GetBrand
    {
        public static Task<GetBrandResult> InvokeAsync(GetBrandArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetBrandResult>("authentik:index/getBrand:getBrand", args ?? new GetBrandArgs(), options.WithDefaults(), Utilities.PackageParameterization());

        public static Output<GetBrandResult> Invoke(GetBrandInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetBrandResult>("authentik:index/getBrand:getBrand", args ?? new GetBrandInvokeArgs(), options.WithDefaults());

        public static Output<GetBrandResult> Invoke(GetBrandInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetBrandResult>("authentik:index/getBrand:getBrand", args ?? new GetBrandInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetBrandArgs : global::Pulumi.InvokeArgs
    {
        [Input("brandingCustomCss")]
        public string? BrandingCustomCss { get; set; }

        [Input("brandingDefaultFlowBackground")]
        public string? BrandingDefaultFlowBackground { get; set; }

        [Input("brandingFavicon")]
        public string? BrandingFavicon { get; set; }

        [Input("brandingLogo")]
        public string? BrandingLogo { get; set; }

        [Input("brandingTitle")]
        public string? BrandingTitle { get; set; }

        [Input("clientCertificates")]
        private List<string>? _clientCertificates;
        public List<string> ClientCertificates
        {
            get => _clientCertificates ?? (_clientCertificates = new List<string>());
            set => _clientCertificates = value;
        }

        [Input("default")]
        public bool? Default { get; set; }

        [Input("defaultApplication")]
        public string? DefaultApplication { get; set; }

        [Input("domain")]
        public string? Domain { get; set; }

        [Input("flowAuthentication")]
        public string? FlowAuthentication { get; set; }

        [Input("flowDeviceCode")]
        public string? FlowDeviceCode { get; set; }

        [Input("flowInvalidation")]
        public string? FlowInvalidation { get; set; }

        [Input("flowRecovery")]
        public string? FlowRecovery { get; set; }

        [Input("flowUnenrollment")]
        public string? FlowUnenrollment { get; set; }

        [Input("flowUserSettings")]
        public string? FlowUserSettings { get; set; }

        [Input("id")]
        public string? Id { get; set; }

        [Input("webCertificate")]
        public string? WebCertificate { get; set; }

        public GetBrandArgs()
        {
        }
        public static new GetBrandArgs Empty => new GetBrandArgs();
    }

    public sealed class GetBrandInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("brandingCustomCss")]
        public Input<string>? BrandingCustomCss { get; set; }

        [Input("brandingDefaultFlowBackground")]
        public Input<string>? BrandingDefaultFlowBackground { get; set; }

        [Input("brandingFavicon")]
        public Input<string>? BrandingFavicon { get; set; }

        [Input("brandingLogo")]
        public Input<string>? BrandingLogo { get; set; }

        [Input("brandingTitle")]
        public Input<string>? BrandingTitle { get; set; }

        [Input("clientCertificates")]
        private InputList<string>? _clientCertificates;
        public InputList<string> ClientCertificates
        {
            get => _clientCertificates ?? (_clientCertificates = new InputList<string>());
            set => _clientCertificates = value;
        }

        [Input("default")]
        public Input<bool>? Default { get; set; }

        [Input("defaultApplication")]
        public Input<string>? DefaultApplication { get; set; }

        [Input("domain")]
        public Input<string>? Domain { get; set; }

        [Input("flowAuthentication")]
        public Input<string>? FlowAuthentication { get; set; }

        [Input("flowDeviceCode")]
        public Input<string>? FlowDeviceCode { get; set; }

        [Input("flowInvalidation")]
        public Input<string>? FlowInvalidation { get; set; }

        [Input("flowRecovery")]
        public Input<string>? FlowRecovery { get; set; }

        [Input("flowUnenrollment")]
        public Input<string>? FlowUnenrollment { get; set; }

        [Input("flowUserSettings")]
        public Input<string>? FlowUserSettings { get; set; }

        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("webCertificate")]
        public Input<string>? WebCertificate { get; set; }

        public GetBrandInvokeArgs()
        {
        }
        public static new GetBrandInvokeArgs Empty => new GetBrandInvokeArgs();
    }


    [OutputType]
    public sealed class GetBrandResult
    {
        public readonly string BrandingCustomCss;
        public readonly string BrandingDefaultFlowBackground;
        public readonly string BrandingFavicon;
        public readonly string BrandingLogo;
        public readonly string BrandingTitle;
        public readonly ImmutableArray<string> ClientCertificates;
        public readonly bool Default;
        public readonly string DefaultApplication;
        public readonly string Domain;
        public readonly string FlowAuthentication;
        public readonly string FlowDeviceCode;
        public readonly string FlowInvalidation;
        public readonly string FlowRecovery;
        public readonly string FlowUnenrollment;
        public readonly string FlowUserSettings;
        public readonly string Id;
        public readonly string WebCertificate;

        [OutputConstructor]
        private GetBrandResult(
            string brandingCustomCss,

            string brandingDefaultFlowBackground,

            string brandingFavicon,

            string brandingLogo,

            string brandingTitle,

            ImmutableArray<string> clientCertificates,

            bool @default,

            string defaultApplication,

            string domain,

            string flowAuthentication,

            string flowDeviceCode,

            string flowInvalidation,

            string flowRecovery,

            string flowUnenrollment,

            string flowUserSettings,

            string id,

            string webCertificate)
        {
            BrandingCustomCss = brandingCustomCss;
            BrandingDefaultFlowBackground = brandingDefaultFlowBackground;
            BrandingFavicon = brandingFavicon;
            BrandingLogo = brandingLogo;
            BrandingTitle = brandingTitle;
            ClientCertificates = clientCertificates;
            Default = @default;
            DefaultApplication = defaultApplication;
            Domain = domain;
            FlowAuthentication = flowAuthentication;
            FlowDeviceCode = flowDeviceCode;
            FlowInvalidation = flowInvalidation;
            FlowRecovery = flowRecovery;
            FlowUnenrollment = flowUnenrollment;
            FlowUserSettings = flowUserSettings;
            Id = id;
            WebCertificate = webCertificate;
        }
    }
}
