// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Authentik
{
    [AuthentikResourceType("authentik:index/policyPassword:PolicyPassword")]
    public partial class PolicyPassword : global::Pulumi.CustomResource
    {
        [Output("amountDigits")]
        public Output<double?> AmountDigits { get; private set; } = null!;

        [Output("amountLowercase")]
        public Output<double?> AmountLowercase { get; private set; } = null!;

        [Output("amountSymbols")]
        public Output<double?> AmountSymbols { get; private set; } = null!;

        [Output("amountUppercase")]
        public Output<double?> AmountUppercase { get; private set; } = null!;

        /// <summary>
        /// Defaults to `false`.
        /// </summary>
        [Output("checkHaveIBeenPwned")]
        public Output<bool?> CheckHaveIBeenPwned { get; private set; } = null!;

        /// <summary>
        /// Defaults to `true`.
        /// </summary>
        [Output("checkStaticRules")]
        public Output<bool?> CheckStaticRules { get; private set; } = null!;

        /// <summary>
        /// Defaults to `false`.
        /// </summary>
        [Output("checkZxcvbn")]
        public Output<bool?> CheckZxcvbn { get; private set; } = null!;

        [Output("errorMessage")]
        public Output<string> ErrorMessage { get; private set; } = null!;

        /// <summary>
        /// Defaults to `false`.
        /// </summary>
        [Output("executionLogging")]
        public Output<bool?> ExecutionLogging { get; private set; } = null!;

        /// <summary>
        /// Defaults to `1`.
        /// </summary>
        [Output("hibpAllowedCount")]
        public Output<double?> HibpAllowedCount { get; private set; } = null!;

        [Output("lengthMin")]
        public Output<double?> LengthMin { get; private set; } = null!;

        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Defaults to `password`.
        /// </summary>
        [Output("passwordField")]
        public Output<string?> PasswordField { get; private set; } = null!;

        [Output("policyPasswordId")]
        public Output<string> PolicyPasswordId { get; private set; } = null!;

        /// <summary>
        /// Defaults to `!\"#$%&amp;'()*+,-./:;&lt;=&gt;?@[\]^_`{|}~`.
        /// </summary>
        [Output("symbolCharset")]
        public Output<string?> SymbolCharset { get; private set; } = null!;

        /// <summary>
        /// Defaults to `2`.
        /// </summary>
        [Output("zxcvbnScoreThreshold")]
        public Output<double?> ZxcvbnScoreThreshold { get; private set; } = null!;


        /// <summary>
        /// Create a PolicyPassword resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public PolicyPassword(string name, PolicyPasswordArgs args, CustomResourceOptions? options = null)
            : base("authentik:index/policyPassword:PolicyPassword", name, args ?? new PolicyPasswordArgs(), MakeResourceOptions(options, ""), Utilities.PackageParameterization())
        {
        }

        private PolicyPassword(string name, Input<string> id, PolicyPasswordState? state = null, CustomResourceOptions? options = null)
            : base("authentik:index/policyPassword:PolicyPassword", name, state, MakeResourceOptions(options, id), Utilities.PackageParameterization())
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing PolicyPassword resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static PolicyPassword Get(string name, Input<string> id, PolicyPasswordState? state = null, CustomResourceOptions? options = null)
        {
            return new PolicyPassword(name, id, state, options);
        }
    }

    public sealed class PolicyPasswordArgs : global::Pulumi.ResourceArgs
    {
        [Input("amountDigits")]
        public Input<double>? AmountDigits { get; set; }

        [Input("amountLowercase")]
        public Input<double>? AmountLowercase { get; set; }

        [Input("amountSymbols")]
        public Input<double>? AmountSymbols { get; set; }

        [Input("amountUppercase")]
        public Input<double>? AmountUppercase { get; set; }

        /// <summary>
        /// Defaults to `false`.
        /// </summary>
        [Input("checkHaveIBeenPwned")]
        public Input<bool>? CheckHaveIBeenPwned { get; set; }

        /// <summary>
        /// Defaults to `true`.
        /// </summary>
        [Input("checkStaticRules")]
        public Input<bool>? CheckStaticRules { get; set; }

        /// <summary>
        /// Defaults to `false`.
        /// </summary>
        [Input("checkZxcvbn")]
        public Input<bool>? CheckZxcvbn { get; set; }

        [Input("errorMessage", required: true)]
        public Input<string> ErrorMessage { get; set; } = null!;

        /// <summary>
        /// Defaults to `false`.
        /// </summary>
        [Input("executionLogging")]
        public Input<bool>? ExecutionLogging { get; set; }

        /// <summary>
        /// Defaults to `1`.
        /// </summary>
        [Input("hibpAllowedCount")]
        public Input<double>? HibpAllowedCount { get; set; }

        [Input("lengthMin")]
        public Input<double>? LengthMin { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Defaults to `password`.
        /// </summary>
        [Input("passwordField")]
        public Input<string>? PasswordField { get; set; }

        [Input("policyPasswordId")]
        public Input<string>? PolicyPasswordId { get; set; }

        /// <summary>
        /// Defaults to `!\"#$%&amp;'()*+,-./:;&lt;=&gt;?@[\]^_`{|}~`.
        /// </summary>
        [Input("symbolCharset")]
        public Input<string>? SymbolCharset { get; set; }

        /// <summary>
        /// Defaults to `2`.
        /// </summary>
        [Input("zxcvbnScoreThreshold")]
        public Input<double>? ZxcvbnScoreThreshold { get; set; }

        public PolicyPasswordArgs()
        {
        }
        public static new PolicyPasswordArgs Empty => new PolicyPasswordArgs();
    }

    public sealed class PolicyPasswordState : global::Pulumi.ResourceArgs
    {
        [Input("amountDigits")]
        public Input<double>? AmountDigits { get; set; }

        [Input("amountLowercase")]
        public Input<double>? AmountLowercase { get; set; }

        [Input("amountSymbols")]
        public Input<double>? AmountSymbols { get; set; }

        [Input("amountUppercase")]
        public Input<double>? AmountUppercase { get; set; }

        /// <summary>
        /// Defaults to `false`.
        /// </summary>
        [Input("checkHaveIBeenPwned")]
        public Input<bool>? CheckHaveIBeenPwned { get; set; }

        /// <summary>
        /// Defaults to `true`.
        /// </summary>
        [Input("checkStaticRules")]
        public Input<bool>? CheckStaticRules { get; set; }

        /// <summary>
        /// Defaults to `false`.
        /// </summary>
        [Input("checkZxcvbn")]
        public Input<bool>? CheckZxcvbn { get; set; }

        [Input("errorMessage")]
        public Input<string>? ErrorMessage { get; set; }

        /// <summary>
        /// Defaults to `false`.
        /// </summary>
        [Input("executionLogging")]
        public Input<bool>? ExecutionLogging { get; set; }

        /// <summary>
        /// Defaults to `1`.
        /// </summary>
        [Input("hibpAllowedCount")]
        public Input<double>? HibpAllowedCount { get; set; }

        [Input("lengthMin")]
        public Input<double>? LengthMin { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Defaults to `password`.
        /// </summary>
        [Input("passwordField")]
        public Input<string>? PasswordField { get; set; }

        [Input("policyPasswordId")]
        public Input<string>? PolicyPasswordId { get; set; }

        /// <summary>
        /// Defaults to `!\"#$%&amp;'()*+,-./:;&lt;=&gt;?@[\]^_`{|}~`.
        /// </summary>
        [Input("symbolCharset")]
        public Input<string>? SymbolCharset { get; set; }

        /// <summary>
        /// Defaults to `2`.
        /// </summary>
        [Input("zxcvbnScoreThreshold")]
        public Input<double>? ZxcvbnScoreThreshold { get; set; }

        public PolicyPasswordState()
        {
        }
        public static new PolicyPasswordState Empty => new PolicyPasswordState();
    }
}
