// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Authentik
{
    [AuthentikResourceType("authentik:index/policyReputation:PolicyReputation")]
    public partial class PolicyReputation : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Defaults to `true`.
        /// </summary>
        [Output("checkIp")]
        public Output<bool?> CheckIp { get; private set; } = null!;

        /// <summary>
        /// Defaults to `true`.
        /// </summary>
        [Output("checkUsername")]
        public Output<bool?> CheckUsername { get; private set; } = null!;

        /// <summary>
        /// Defaults to `false`.
        /// </summary>
        [Output("executionLogging")]
        public Output<bool?> ExecutionLogging { get; private set; } = null!;

        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("policyReputationId")]
        public Output<string> PolicyReputationId { get; private set; } = null!;

        /// <summary>
        /// Defaults to `10`.
        /// </summary>
        [Output("threshold")]
        public Output<double?> Threshold { get; private set; } = null!;


        /// <summary>
        /// Create a PolicyReputation resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public PolicyReputation(string name, PolicyReputationArgs? args = null, CustomResourceOptions? options = null)
            : base("authentik:index/policyReputation:PolicyReputation", name, args ?? new PolicyReputationArgs(), MakeResourceOptions(options, ""), Utilities.PackageParameterization())
        {
        }

        private PolicyReputation(string name, Input<string> id, PolicyReputationState? state = null, CustomResourceOptions? options = null)
            : base("authentik:index/policyReputation:PolicyReputation", name, state, MakeResourceOptions(options, id), Utilities.PackageParameterization())
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing PolicyReputation resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static PolicyReputation Get(string name, Input<string> id, PolicyReputationState? state = null, CustomResourceOptions? options = null)
        {
            return new PolicyReputation(name, id, state, options);
        }
    }

    public sealed class PolicyReputationArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Defaults to `true`.
        /// </summary>
        [Input("checkIp")]
        public Input<bool>? CheckIp { get; set; }

        /// <summary>
        /// Defaults to `true`.
        /// </summary>
        [Input("checkUsername")]
        public Input<bool>? CheckUsername { get; set; }

        /// <summary>
        /// Defaults to `false`.
        /// </summary>
        [Input("executionLogging")]
        public Input<bool>? ExecutionLogging { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("policyReputationId")]
        public Input<string>? PolicyReputationId { get; set; }

        /// <summary>
        /// Defaults to `10`.
        /// </summary>
        [Input("threshold")]
        public Input<double>? Threshold { get; set; }

        public PolicyReputationArgs()
        {
        }
        public static new PolicyReputationArgs Empty => new PolicyReputationArgs();
    }

    public sealed class PolicyReputationState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Defaults to `true`.
        /// </summary>
        [Input("checkIp")]
        public Input<bool>? CheckIp { get; set; }

        /// <summary>
        /// Defaults to `true`.
        /// </summary>
        [Input("checkUsername")]
        public Input<bool>? CheckUsername { get; set; }

        /// <summary>
        /// Defaults to `false`.
        /// </summary>
        [Input("executionLogging")]
        public Input<bool>? ExecutionLogging { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("policyReputationId")]
        public Input<string>? PolicyReputationId { get; set; }

        /// <summary>
        /// Defaults to `10`.
        /// </summary>
        [Input("threshold")]
        public Input<double>? Threshold { get; set; }

        public PolicyReputationState()
        {
        }
        public static new PolicyReputationState Empty => new PolicyReputationState();
    }
}
