// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Authentik
{
    [AuthentikResourceType("authentik:index/propertyMappingSourceLdap:PropertyMappingSourceLdap")]
    public partial class PropertyMappingSourceLdap : global::Pulumi.CustomResource
    {
        [Output("expression")]
        public Output<string> Expression { get; private set; } = null!;

        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("propertyMappingSourceLdapId")]
        public Output<string> PropertyMappingSourceLdapId { get; private set; } = null!;


        /// <summary>
        /// Create a PropertyMappingSourceLdap resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public PropertyMappingSourceLdap(string name, PropertyMappingSourceLdapArgs args, CustomResourceOptions? options = null)
            : base("authentik:index/propertyMappingSourceLdap:PropertyMappingSourceLdap", name, args ?? new PropertyMappingSourceLdapArgs(), MakeResourceOptions(options, ""), Utilities.PackageParameterization())
        {
        }

        private PropertyMappingSourceLdap(string name, Input<string> id, PropertyMappingSourceLdapState? state = null, CustomResourceOptions? options = null)
            : base("authentik:index/propertyMappingSourceLdap:PropertyMappingSourceLdap", name, state, MakeResourceOptions(options, id), Utilities.PackageParameterization())
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing PropertyMappingSourceLdap resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static PropertyMappingSourceLdap Get(string name, Input<string> id, PropertyMappingSourceLdapState? state = null, CustomResourceOptions? options = null)
        {
            return new PropertyMappingSourceLdap(name, id, state, options);
        }
    }

    public sealed class PropertyMappingSourceLdapArgs : global::Pulumi.ResourceArgs
    {
        [Input("expression", required: true)]
        public Input<string> Expression { get; set; } = null!;

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("propertyMappingSourceLdapId")]
        public Input<string>? PropertyMappingSourceLdapId { get; set; }

        public PropertyMappingSourceLdapArgs()
        {
        }
        public static new PropertyMappingSourceLdapArgs Empty => new PropertyMappingSourceLdapArgs();
    }

    public sealed class PropertyMappingSourceLdapState : global::Pulumi.ResourceArgs
    {
        [Input("expression")]
        public Input<string>? Expression { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("propertyMappingSourceLdapId")]
        public Input<string>? PropertyMappingSourceLdapId { get; set; }

        public PropertyMappingSourceLdapState()
        {
        }
        public static new PropertyMappingSourceLdapState Empty => new PropertyMappingSourceLdapState();
    }
}
