// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Authentik
{
    [AuthentikResourceType("authentik:index/rbacRole:RbacRole")]
    public partial class RbacRole : global::Pulumi.CustomResource
    {
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("rbacRoleId")]
        public Output<string> RbacRoleId { get; private set; } = null!;


        /// <summary>
        /// Create a RbacRole resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public RbacRole(string name, RbacRoleArgs? args = null, CustomResourceOptions? options = null)
            : base("authentik:index/rbacRole:RbacRole", name, args ?? new RbacRoleArgs(), MakeResourceOptions(options, ""), Utilities.PackageParameterization())
        {
        }

        private RbacRole(string name, Input<string> id, RbacRoleState? state = null, CustomResourceOptions? options = null)
            : base("authentik:index/rbacRole:RbacRole", name, state, MakeResourceOptions(options, id), Utilities.PackageParameterization())
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing RbacRole resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static RbacRole Get(string name, Input<string> id, RbacRoleState? state = null, CustomResourceOptions? options = null)
        {
            return new RbacRole(name, id, state, options);
        }
    }

    public sealed class RbacRoleArgs : global::Pulumi.ResourceArgs
    {
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("rbacRoleId")]
        public Input<string>? RbacRoleId { get; set; }

        public RbacRoleArgs()
        {
        }
        public static new RbacRoleArgs Empty => new RbacRoleArgs();
    }

    public sealed class RbacRoleState : global::Pulumi.ResourceArgs
    {
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("rbacRoleId")]
        public Input<string>? RbacRoleId { get; set; }

        public RbacRoleState()
        {
        }
        public static new RbacRoleState Empty => new RbacRoleState();
    }
}
