---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app librespeed
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  timeout: 10m
  interval: 1h
  driftDetection:
    mode: enabled
  values:
    controllers:
      *app :
        containers:
          *app :
            image:
              repository: ghcr.io/librespeed/speedtest
              tag: latest@sha256:7908b0be647956181f6f93c1c6ee6a4bb9a5767710af5409220369d5b4c1f828
            resources:
              requests:
                cpu: 200m
                memory: 32Mi
              limits:
                memory: 128Mi

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false

    service:
      *app :
        ports:
          http:
            port: &port 8080

    route:
      internal:
        parentRefs:
          - name: internal
            namespace: network
            kind: Gateway
        hostnames:
          - "${APP}.${CLUSTER_DOMAIN}"
        kind: HTTPRoute
        rules:
          - backendRefs:
              - identifier: *app
                port: *port
