---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app librespeed
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  timeout: 10m
  interval: 1h
  driftDetection:
    mode: enabled
  values:
    controllers:
      *app :
        containers:
          *app :
            image:
              repository: ghcr.io/librespeed/speedtest
              tag: latest@sha256:a57731182416f08e61d0d93595b0874b2f21394393510c8befadb428303f7e26
            resources:
              requests:
                cpu: 50m
                memory: 32Mi
              limits:
                memory: 128Mi
            env:
              USE_NEW_DESIGN: true
              TELEMETRY: false
              ENABLE_ID_OBFUSCATION: false
              REDACT_IP_ADDRESSES: false
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false

    service:
      *app :
        ports:
          http:
            port: &port 8080

    route:
      internal:
        parentRefs:
          - name: internal
            namespace: network
            kind: Gateway
        hostnames:
          - "${APP}.${CLUSTER_DOMAIN}"
        kind: HTTPRoute
        rules:
          - backendRefs:
              - identifier: *app
                port: *port
