---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: authentik-server
  namespace: sgc
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: authentik
      app.kubernetes.io/component: server
