---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # renovate: datasource=github-releases depName=kubernetes-sigs/gateway-api
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.5.1/experimental-install.yaml
  # renovate: datasource=helm depName=traefik registryUrl=https://traefik.github.io/charts
  - https://raw.githubusercontent.com/traefik/traefik-helm-chart/v40.2.0/traefik/crds/traefik.io_ingressroutes.yaml
  # renovate: datasource=helm depName=traefik registryUrl=https://traefik.github.io/charts
  - https://raw.githubusercontent.com/traefik/traefik-helm-chart/v40.2.0/traefik/crds/traefik.io_ingressroutetcps.yaml
  # renovate: datasource=helm depName=traefik registryUrl=https://traefik.github.io/charts
  - https://raw.githubusercontent.com/traefik/traefik-helm-chart/v40.2.0/traefik/crds/traefik.io_ingressrouteudps.yaml
  # renovate: datasource=helm depName=traefik registryUrl=https://traefik.github.io/charts
  - https://raw.githubusercontent.com/traefik/traefik-helm-chart/v40.2.0/traefik/crds/traefik.io_middlewares.yaml
  # renovate: datasource=helm depName=traefik registryUrl=https://traefik.github.io/charts
  - https://raw.githubusercontent.com/traefik/traefik-helm-chart/v40.2.0/traefik/crds/traefik.io_middlewaretcps.yaml
  # renovate: datasource=helm depName=traefik registryUrl=https://traefik.github.io/charts
  - https://raw.githubusercontent.com/traefik/traefik-helm-chart/v40.2.0/traefik/crds/traefik.io_serverstransports.yaml
  # renovate: datasource=helm depName=traefik registryUrl=https://traefik.github.io/charts
  - https://raw.githubusercontent.com/traefik/traefik-helm-chart/v40.2.0/traefik/crds/traefik.io_serverstransporttcps.yaml
  # renovate: datasource=helm depName=traefik registryUrl=https://traefik.github.io/charts
  - https://raw.githubusercontent.com/traefik/traefik-helm-chart/v40.2.0/traefik/crds/traefik.io_tlsoptions.yaml
  # renovate: datasource=helm depName=traefik registryUrl=https://traefik.github.io/charts
  - https://raw.githubusercontent.com/traefik/traefik-helm-chart/v40.2.0/traefik/crds/traefik.io_tlsstores.yaml
  # renovate: datasource=helm depName=traefik registryUrl=https://traefik.github.io/charts
  - https://raw.githubusercontent.com/traefik/traefik-helm-chart/v40.2.0/traefik/crds/traefik.io_traefikservices.yaml
