// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Driscoll.V1
{

    [OutputType]
    public sealed class ApplicationDefinitionSpecUptimeHttp
    {
        public readonly ImmutableArray<string> Accepted_statuscodes;
        public readonly bool Active;
        public readonly string AuthMethod;
        public readonly string Auth_domain;
        public readonly string Auth_workstation;
        public readonly string Basic_auth_pass;
        public readonly string Basic_auth_user;
        public readonly string Body;
        public readonly string Description;
        public readonly bool Expiry_notification;
        public readonly string Http_body_encoding;
        public readonly bool Ignore_tls;
        public readonly int Interval;
        public readonly int Max_redirects;
        public readonly int Max_retries;
        public readonly string Method;
        public readonly string Name;
        public readonly string Oauth_auth_method;
        public readonly string Oauth_client_id;
        public readonly string Oauth_client_secret;
        public readonly string Oauth_scopes;
        public readonly string Oauth_token_url;
        public readonly int Parent;
        public readonly string Parent_name;
        public readonly string Proxy_id;
        public readonly int Resend_interval;
        public readonly int Retry_interval;
        public readonly int Timeout;
        public readonly string Tls_ca;
        public readonly string Tls_cert;
        public readonly string Tls_key;
        public readonly bool Upside_down;
        public readonly string Url;

        [OutputConstructor]
        private ApplicationDefinitionSpecUptimeHttp(
            ImmutableArray<string> accepted_statuscodes,

            bool active,

            string authMethod,

            string auth_domain,

            string auth_workstation,

            string basic_auth_pass,

            string basic_auth_user,

            string body,

            string description,

            bool expiry_notification,

            string http_body_encoding,

            bool ignore_tls,

            int interval,

            int max_redirects,

            int max_retries,

            string method,

            string name,

            string oauth_auth_method,

            string oauth_client_id,

            string oauth_client_secret,

            string oauth_scopes,

            string oauth_token_url,

            int parent,

            string parent_name,

            string proxy_id,

            int resend_interval,

            int retry_interval,

            int timeout,

            string tls_ca,

            string tls_cert,

            string tls_key,

            bool upside_down,

            string url)
        {
            Accepted_statuscodes = accepted_statuscodes;
            Active = active;
            AuthMethod = authMethod;
            Auth_domain = auth_domain;
            Auth_workstation = auth_workstation;
            Basic_auth_pass = basic_auth_pass;
            Basic_auth_user = basic_auth_user;
            Body = body;
            Description = description;
            Expiry_notification = expiry_notification;
            Http_body_encoding = http_body_encoding;
            Ignore_tls = ignore_tls;
            Interval = interval;
            Max_redirects = max_redirects;
            Max_retries = max_retries;
            Method = method;
            Name = name;
            Oauth_auth_method = oauth_auth_method;
            Oauth_client_id = oauth_client_id;
            Oauth_client_secret = oauth_client_secret;
            Oauth_scopes = oauth_scopes;
            Oauth_token_url = oauth_token_url;
            Parent = parent;
            Parent_name = parent_name;
            Proxy_id = proxy_id;
            Resend_interval = resend_interval;
            Retry_interval = retry_interval;
            Timeout = timeout;
            Tls_ca = tls_ca;
            Tls_cert = tls_cert;
            Tls_key = tls_key;
            Upside_down = upside_down;
            Url = url;
        }
    }
}
