# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:xEfSpCq9frpO/R3tQ2xrObFyCsXNfFqNua3K/vZbK/c=,iv:e/ZHp5iF98ZWOZwUMm8GUHhAHz5zHvyW/AXtdxU4LEY=,tag:bp7Nkw0LPmXHJE/MDF254w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyampQbElVMThyLzZVTzkv
        VjJFOWRlbHJXbWVDU2VzbUFIMGkxNVh6YVVZCnpWU2Jjb21rR2JvMGdHcHVOWTJn
        ZS82OEdUQzlqcGRjaVI2TE5MdjczVGsKLS0tIHpJQXFtMGt3eVBDbk4rdElpQndl
        VUlGSjVWRlB6QWRycWxWRVU3aFkyM0UKGq6yp6rHd+0yPluWcZmcONlmJ62eSoNt
        aDyBYVXPKPDiIs+hl/EusmUPw5CpYUQGeEhLO9/WepC9bMbUMk6oUw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eurl2t7pepw66guv8m7lxh5fjhs4t4frsntqjp08lmypwudlsp7qdusgnf
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndm5JK0wycHVFM0hvVUpI
        YTlHRjR0QUdVYU05dEJDU25oT2hmdnhNY2tJCms3NkRQNW9FSWxsVDNOd3VvSWh5
        bUdGcVVDaWZjRU1pVlo1WnR4Zmw5OUkKLS0tIENIQzc1eFN4L2tCNDBIaVpCTGRm
        eFM0aDhDUGFDRWdRZWxva01sZjJnbW8KGhrLLdnBhfIaoHoI/gTWDo4qcRwDCG8V
        bBuBVzKVFrDPXPYWzCsBtszCL7uFq9cHsCKApy4dF5HtkIZNwFDT9Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age150z0s36kl9vud8728c5e4zqq6nmyywekk76rwvjclcsfc8mrxuuqr0qfg6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-04-17T04:40:29Z"
  mac: ENC[AES256_GCM,data:KKJyOSg+7Lo8pLCsqYSICipN5JngbnKTFl4m7VkrMNT/KrYfycThf930jb3rgLDG5hl2RgQjrJeafbfz90xzPDNVwSa6HCkVbTrmLaJCUAdCHx5lDZ12/CFxE35F+ZcM/cFgABFMxn64/FIGxTXX5PE5wN1/UZU6RzDfLqXCd4A=,iv:GkPWIRGlS1Oy9ljkdRJ/JuZaOYHw83YbvGCCSH+ojjE=,tag:IT9JOPQ8wDLaw+4CICw2+g==,type:str]
  mac_only_encrypted: true
  version: 3.10.1
