// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using Tailscale.Client.Tailnet.Item.Logging.Item.StreamNamespace;
namespace Tailscale.Client.Tailnet.Item.Logging.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \tailnet\{tailnet}\logging\{logType}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithLogTypeItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The stream property</summary>
        public global::Tailscale.Client.Tailnet.Item.Logging.Item.StreamNamespace.StreamRequestBuilder Stream
        {
            get => new global::Tailscale.Client.Tailnet.Item.Logging.Item.StreamNamespace.StreamRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Tailscale.Client.Tailnet.Item.Logging.Item.WithLogTypeItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithLogTypeItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tailnet/{tailnet}/logging/{logType}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Tailscale.Client.Tailnet.Item.Logging.Item.WithLogTypeItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithLogTypeItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tailnet/{tailnet}/logging/{logType}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
