---
# yaml-language-server: $schema=https://raw.githubusercontent.com/david-driscoll/stargate-command-cluster/refs/heads/main/schemas/definition.schema.json
apiVersion: driscoll.dev/v1
kind: ApplicationDefinition
metadata:
  name: technitium
spec:
  name: Technitium DNS
  category: ${CLUSTER_TITLE}
  description: Technitium DNS cluster node
  url: &url https://${CLUSTER_KEY}.dns.${ROOT_DOMAIN}:53443
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/technitium.png
  access_policy:
    groups:
      - admins
  authentik:
    oauth2:
      clientType: confidential
      allowedRedirectUris:
      - url: "https://${CLUSTER_KEY}.dns.${ROOT_DOMAIN}:53443/sso/callback"
      propertyMappings:
        - email
        - openid
        - profile
      includeClaimsInIdToken: true
      subMode: user_email
  gatus:
    - group: ${CLUSTER_TITLE}
      url: *url
      method: GET
      conditions:
        - "[STATUS] < 400"
    - group: ${CLUSTER_TITLE}
      url: https://${CLUSTER_KEY}.dns.${ROOT_DOMAIN}
      method: GET
      conditions:
        - "[STATUS] == 200"
