---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-env
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshPolicy: Periodic
  refreshInterval: 4m
  target:
    name: ${APP}-env
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        annotations:
          reloader.stakater.com/auto: "true"
  data:
    - secretKey: DNS_SERVER_ADMIN_PASSWORD
      remoteRef:
        key: "Technitium Password"
        property: password
    - secretKey: DNS_SERVER_SSO_AUTHORITY
      remoteRef:
        key: "sgc-technitium-oidc-credentials"
        property: issuer
    - secretKey: DNS_SERVER_SSO_CLIENT_ID
      remoteRef:
        key: "sgc-technitium-oidc-credentials"
        property: client_id
    - secretKey: DNS_SERVER_SSO_CLIENT_SECRET
      remoteRef:
        key: "sgc-technitium-oidc-credentials"
        property: client_secret
