---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-postgres-password
stringData:
  username: "crowdsec"
  database: "crowdsec"
  port: "5432"
  hostname: "postgres-rw.database.svc.cluster.local"
  password: "e5418d747d48495fa644e6f2f2091460"
---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: authentik-postgres-password
stringData:
  username: "authentik"
  database: "authentik"
  port: "5432"
  hostname: "postgres-rw.database.svc.cluster.local"
  password: "d25e8e12ab8e400285a35014cd8707f9"
---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: oxycloud-postgres-password
stringData:
  username: "oxycloud"
  database: "oxycloud"
  port: "5432"
  hostname: "postgres-rw.database.svc.cluster.local"
  password: "b0372d3d7dfb4ffa94329231ee495075"
---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: postgres-user-password
stringData:
  username: "postgres-user"
  database: "postgres-user"
  port: "5432"
  hostname: "postgres-rw.database.svc.cluster.local"
  password: "15b0b1e2feb470affa80ae058ee27bfb39bed84152ceae7bfc8cfe5771db1178"
---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: postgres-superuser-password
stringData:
  username: "postgres-superuser"
  database: "postgres-superuser"
  port: "5432"
  hostname: "postgres-rw.database.svc.cluster.local"
  password: "74fb25c6b554414babb7dc79aa0bef25"
