---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-postgres
stringData:
  username: "crowdsec"
  database: "crowdsec"
  port: "5432"
  hostname: "postgres-rw.database.svc.cluster.local"
  password: "a2c79e25e61a48789860a8a6aa5e8cd6"
---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: authentik-postgres
stringData:
  username: "authentik"
  database: "authentik"
  port: "5432"
  hostname: "postgres-rw.database.svc.cluster.local"
  password: "74989175745043dda36e56d5648f1c6a"
---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: oxycloud-postgres
stringData:
  username: "oxycloud"
  database: "oxycloud"
  port: "5432"
  hostname: "postgres-rw.database.svc.cluster.local"
  password: "004f7dfd498147a496e75f172a5f77de"
---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: postgres-user
stringData:
  username: "postgres-user"
  database: "postgres-user"
  port: "5432"
  hostname: "postgres-rw.database.svc.cluster.local"
  password: "15b0b1e2feb470affa80ae058ee27bfb39bed84152ceae7bfc8cfe5771db1178"
---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: postgres-superuser
stringData:
  username: "postgres-superuser"
  database: "postgres-superuser"
  port: "5432"
  hostname: "postgres-rw.database.svc.cluster.local"
  password: "74fb25c6b554414babb7dc79aa0bef25"
