apiVersion: v1
kind: Secret
metadata:
  name: postgres-superuser-password
stringData:
  password: ENC[AES256_GCM,data:BIBuMwRJKqIoRuMu8bSb0AHHsOOXKHv19A5HHS3m42WIohrQxRY5gX3RimcKMEkB91WUnBDofwMnlB3bkU3BTg==,iv:d+J8QgFT4LpVZmTGgU3Fn6S0oEvvfCt9FY01YXSqBQ8=,tag:efVyOCqabFjcy40/kn77Jw==,type:str]
  username: ENC[AES256_GCM,data:4ij66r6s6qU=,iv:WM/3+hbgTQEiUompS25n1WJnNmPGAlU093cPsVHSYdw=,tag:0kLfv3jUODYgLVwtZm6IsA==,type:str]
  database: ENC[AES256_GCM,data:uVwL0NN/czw=,iv:plL+emzQcUehchBMeUBI72Oh4ZU8waEMPAocgtAW4bA=,tag:t4DcE+kzeAoGrEsk+0P5nw==,type:str]
  port: ENC[AES256_GCM,data:uhp6pQ==,iv:WG7qUr1T0rrpDN+6K8eXuQoEMXwgWsCMjLW4Mdi8ohU=,tag:TlZP3h2ju5u7FO8bOeX24A==,type:str]
  hostname: ENC[AES256_GCM,data:CESz5s1NYFtSPuKEMTIHZzx2wQqv/ZcgmHG3Xrk2GvDC8JupYXA=,iv:6wQ8dy2B8vIumjX7OTdK1UfXuSKCOa01iuJuAHdvucE=,tag:UFrPsY0shtXjQXS1DbgVsA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYYjM5cVhrY3A4SU9MTmlk
        ZVA3bUtyVVV1cm5iU3QrTWRqNFN4Z3dVRFFFCkQ4WExsN3VCZDU3cTZHeUR6Tk5o
        NWhWWmp1RlFiQWhPQW5jc2ZEZ1h3dncKLS0tIGZYV1NiWXlac0p4TVJ5eUkzMWhO
        WmIzejVuWkt3MnNVa01OMm5DU0NOUkEKMHA0yKjOTvnHSM4VRIVBFaBksh1xgX7u
        q3RjZ2l/VypqtjnqrAw/7RR2o2g5ooYn56FgfAPQB9nkcOkhf2WWhg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eurl2t7pepw66guv8m7lxh5fjhs4t4frsntqjp08lmypwudlsp7qdusgnf
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqcXlRYVBFNy9pQjhiQ1ND
        WC9QUFFpM0plZ2VIdU9hbXZ0QnIydjg5V1JBCjdnN2dXN1NCSUhEcEd0MVVuSlQ5
        R0UvcmE1NnZDNTlHbElRazgxWC9iUmsKLS0tIE5qV0o1eE4rSWxSREZOZWtCcXNS
        NGxUT0VtK2Z1YVpqY3E2di8wZTJDN3MKVni2p1g7/Idl8lSzx2JFkphccgtQGZmL
        ZUY2ONdSLQbj7eqHgj3Hi1v4N/Jik4why1BX+KPEF65Ke4lBBomJUg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age150z0s36kl9vud8728c5e4zqq6nmyywekk76rwvjclcsfc8mrxuuqr0qfg6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-13T16:11:00Z"
  mac: ENC[AES256_GCM,data:fDTwuFMF8CQhivm6wdMXKF1gYBYhzTRxPmYY4a4xRM/KhFSC+85KD6SEJw37WjoOVufic5fNXG1g8HWJuzFaTdYwXKGllfN0IFKbXWs8qshOTeVbuB/XT8SxTsUh47ZeUt272i7SMgdykp/D4jH1NvtisKUvA4X1iRZiTVoBM3Q=,iv:hKKnIkewcb34p3XIdcFa3MKv+pFBD4UMKn3vJwgihYU=,tag:97eLA624GiM4FJBBqRx0cQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-user-password
stringData:
  password: ENC[AES256_GCM,data:mmZacTAoI27VkiI6JjxTFLsEhpai86PZskTOkGDZhHw=,iv:kzbe8x/I0iZ5BNdoZigUIp4hjhd6088dzqAo29SljwQ=,tag:abwbTJvIiGZb9ZFF0LvPgw==,type:str]
  username: ENC[AES256_GCM,data:X263+tUhDE92E8PwT2KM1Q==,iv:L6iFrQb/ymFE9HUqviDV6HIYdSetqLwwR8X5zZKomcs=,tag:p6E08I4rHxKgYlxsL3hAGQ==,type:str]
  database: ENC[AES256_GCM,data:GwG9alWnJmQ=,iv:xGLnub2ANNB29xoGJGGZN2C546H0OeXp43keHDi7UfQ=,tag:CPIvX2tZ4V+vaesQhbknPA==,type:str]
  port: ENC[AES256_GCM,data:4RmeCw==,iv:Zuxcyh77vIXalM9mdna9bMsHvTqI9iASMo/TVxCRpS4=,tag:bFsDJgm6NodTRuevjKCVlg==,type:str]
  hostname: ENC[AES256_GCM,data:pK1WD2N0wceEVPfSbQcRZ25VwAf+ncckG92pJiIqyaNv3TLJAEA=,iv:FIf1k9M7rr7ZOOe9Nzb7euS6oyykyXAVrszUyIGEFrw=,tag:MmZoSm/sUggHMRlriJn3nQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYYjM5cVhrY3A4SU9MTmlk
        ZVA3bUtyVVV1cm5iU3QrTWRqNFN4Z3dVRFFFCkQ4WExsN3VCZDU3cTZHeUR6Tk5o
        NWhWWmp1RlFiQWhPQW5jc2ZEZ1h3dncKLS0tIGZYV1NiWXlac0p4TVJ5eUkzMWhO
        WmIzejVuWkt3MnNVa01OMm5DU0NOUkEKMHA0yKjOTvnHSM4VRIVBFaBksh1xgX7u
        q3RjZ2l/VypqtjnqrAw/7RR2o2g5ooYn56FgfAPQB9nkcOkhf2WWhg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eurl2t7pepw66guv8m7lxh5fjhs4t4frsntqjp08lmypwudlsp7qdusgnf
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqcXlRYVBFNy9pQjhiQ1ND
        WC9QUFFpM0plZ2VIdU9hbXZ0QnIydjg5V1JBCjdnN2dXN1NCSUhEcEd0MVVuSlQ5
        R0UvcmE1NnZDNTlHbElRazgxWC9iUmsKLS0tIE5qV0o1eE4rSWxSREZOZWtCcXNS
        NGxUT0VtK2Z1YVpqY3E2di8wZTJDN3MKVni2p1g7/Idl8lSzx2JFkphccgtQGZmL
        ZUY2ONdSLQbj7eqHgj3Hi1v4N/Jik4why1BX+KPEF65Ke4lBBomJUg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age150z0s36kl9vud8728c5e4zqq6nmyywekk76rwvjclcsfc8mrxuuqr0qfg6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-13T16:11:00Z"
  mac: ENC[AES256_GCM,data:fDTwuFMF8CQhivm6wdMXKF1gYBYhzTRxPmYY4a4xRM/KhFSC+85KD6SEJw37WjoOVufic5fNXG1g8HWJuzFaTdYwXKGllfN0IFKbXWs8qshOTeVbuB/XT8SxTsUh47ZeUt272i7SMgdykp/D4jH1NvtisKUvA4X1iRZiTVoBM3Q=,iv:hKKnIkewcb34p3XIdcFa3MKv+pFBD4UMKn3vJwgihYU=,tag:97eLA624GiM4FJBBqRx0cQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
  name: authentik-postgres-password
stringData:
  username: ENC[AES256_GCM,data:R2f/8F03nmyz,iv:k3wfKngw/kscENazSJOQg0622vRbR81+B5XQW5aatVk=,tag:YSng2+vGOeX/ameeWB2duA==,type:str]
  database: ENC[AES256_GCM,data:TF8zaSg8vIk7,iv:2/p9OIYnkTSlsVTe0Cky5l66jGtIZRt0i9UPazXlLR8=,tag:9pNg+cs5Pnu/DysK0Kdy4A==,type:str]
  port: ENC[AES256_GCM,data:stL4gQ==,iv:p/ltJlt9sjcWXotlwvxseylJ/9H0SXA/mAJLaAG0ZOM=,tag:o8rjc+TbVlEoWdDWrORrtQ==,type:str]
  hostname: ENC[AES256_GCM,data:hDgwWJ5Bu+PAkd8mtN2qEerS80RT/MqhkS1/4cybU/pxZ/kdVvs=,iv:ixK8b+TwfWaIgdzrQOOgDg6zgdLBNBvdbReVAFTW0tc=,tag:a06qjASnZgzJs4Jpd46FFg==,type:str]
  password: ENC[AES256_GCM,data:54cUOXsg8i0ACrMSTtwEsasXaqTjrSFGYJuFU0LZWBY=,iv:E2QODfyjj89G1V1NnKPl9CHxMFNGnRBYhQSRiYe+PUg=,tag:g5c19aeLeNPDDe8nGvPmLA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYYjM5cVhrY3A4SU9MTmlk
        ZVA3bUtyVVV1cm5iU3QrTWRqNFN4Z3dVRFFFCkQ4WExsN3VCZDU3cTZHeUR6Tk5o
        NWhWWmp1RlFiQWhPQW5jc2ZEZ1h3dncKLS0tIGZYV1NiWXlac0p4TVJ5eUkzMWhO
        WmIzejVuWkt3MnNVa01OMm5DU0NOUkEKMHA0yKjOTvnHSM4VRIVBFaBksh1xgX7u
        q3RjZ2l/VypqtjnqrAw/7RR2o2g5ooYn56FgfAPQB9nkcOkhf2WWhg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eurl2t7pepw66guv8m7lxh5fjhs4t4frsntqjp08lmypwudlsp7qdusgnf
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqcXlRYVBFNy9pQjhiQ1ND
        WC9QUFFpM0plZ2VIdU9hbXZ0QnIydjg5V1JBCjdnN2dXN1NCSUhEcEd0MVVuSlQ5
        R0UvcmE1NnZDNTlHbElRazgxWC9iUmsKLS0tIE5qV0o1eE4rSWxSREZOZWtCcXNS
        NGxUT0VtK2Z1YVpqY3E2di8wZTJDN3MKVni2p1g7/Idl8lSzx2JFkphccgtQGZmL
        ZUY2ONdSLQbj7eqHgj3Hi1v4N/Jik4why1BX+KPEF65Ke4lBBomJUg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age150z0s36kl9vud8728c5e4zqq6nmyywekk76rwvjclcsfc8mrxuuqr0qfg6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-13T16:11:00Z"
  mac: ENC[AES256_GCM,data:fDTwuFMF8CQhivm6wdMXKF1gYBYhzTRxPmYY4a4xRM/KhFSC+85KD6SEJw37WjoOVufic5fNXG1g8HWJuzFaTdYwXKGllfN0IFKbXWs8qshOTeVbuB/XT8SxTsUh47ZeUt272i7SMgdykp/D4jH1NvtisKUvA4X1iRZiTVoBM3Q=,iv:hKKnIkewcb34p3XIdcFa3MKv+pFBD4UMKn3vJwgihYU=,tag:97eLA624GiM4FJBBqRx0cQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
