// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Authentik
{
    [AuthentikResourceType("authentik:index/eventRule:EventRule")]
    public partial class EventRule : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Send notification to event user Defaults to `false`.
        /// </summary>
        [Output("destinationEventUser")]
        public Output<bool?> DestinationEventUser { get; private set; } = null!;

        /// <summary>
        /// Group to send notification to
        /// </summary>
        [Output("destinationGroup")]
        public Output<string?> DestinationGroup { get; private set; } = null!;

        [Output("eventRuleId")]
        public Output<string> EventRuleId { get; private set; } = null!;

        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Allowed values: - `notice` - `warning` - `alert` Defaults to `warning`.
        /// </summary>
        [Output("severity")]
        public Output<string?> Severity { get; private set; } = null!;

        [Output("transports")]
        public Output<ImmutableArray<string>> Transports { get; private set; } = null!;


        /// <summary>
        /// Create a EventRule resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public EventRule(string name, EventRuleArgs args, CustomResourceOptions? options = null)
            : base("authentik:index/eventRule:EventRule", name, args ?? new EventRuleArgs(), MakeResourceOptions(options, ""), Utilities.PackageParameterization())
        {
        }

        private EventRule(string name, Input<string> id, EventRuleState? state = null, CustomResourceOptions? options = null)
            : base("authentik:index/eventRule:EventRule", name, state, MakeResourceOptions(options, id), Utilities.PackageParameterization())
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing EventRule resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static EventRule Get(string name, Input<string> id, EventRuleState? state = null, CustomResourceOptions? options = null)
        {
            return new EventRule(name, id, state, options);
        }
    }

    public sealed class EventRuleArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Send notification to event user Defaults to `false`.
        /// </summary>
        [Input("destinationEventUser")]
        public Input<bool>? DestinationEventUser { get; set; }

        /// <summary>
        /// Group to send notification to
        /// </summary>
        [Input("destinationGroup")]
        public Input<string>? DestinationGroup { get; set; }

        [Input("eventRuleId")]
        public Input<string>? EventRuleId { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Allowed values: - `notice` - `warning` - `alert` Defaults to `warning`.
        /// </summary>
        [Input("severity")]
        public Input<string>? Severity { get; set; }

        [Input("transports", required: true)]
        private InputList<string>? _transports;
        public InputList<string> Transports
        {
            get => _transports ?? (_transports = new InputList<string>());
            set => _transports = value;
        }

        public EventRuleArgs()
        {
        }
        public static new EventRuleArgs Empty => new EventRuleArgs();
    }

    public sealed class EventRuleState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Send notification to event user Defaults to `false`.
        /// </summary>
        [Input("destinationEventUser")]
        public Input<bool>? DestinationEventUser { get; set; }

        /// <summary>
        /// Group to send notification to
        /// </summary>
        [Input("destinationGroup")]
        public Input<string>? DestinationGroup { get; set; }

        [Input("eventRuleId")]
        public Input<string>? EventRuleId { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Allowed values: - `notice` - `warning` - `alert` Defaults to `warning`.
        /// </summary>
        [Input("severity")]
        public Input<string>? Severity { get; set; }

        [Input("transports")]
        private InputList<string>? _transports;
        public InputList<string> Transports
        {
            get => _transports ?? (_transports = new InputList<string>());
            set => _transports = value;
        }

        public EventRuleState()
        {
        }
        public static new EventRuleState Empty => new EventRuleState();
    }
}
